from app.database.session import SessionLocal
from app.models.medicine import Medicine

medicines = [
    {
        "name": "Metformin",
        "generic_name": "Metformin hydrochloride",
        "drug_class": "Biguanide",
        "standard_dosage": "500-1000 mg orally twice daily with meals",
        "side_effects": "Nausea, diarrhea, abdominal discomfort, vitamin B12 deficiency",
        "contraindications": "Severe renal impairment, metabolic acidosis",
        "guideline_source": "ADA",
    },
    {
        "name": "Glimepiride",
        "generic_name": "Glimepiride",
        "drug_class": "Sulfonylurea",
        "standard_dosage": "1-8 mg orally once daily",
        "side_effects": "Hypoglycemia, weight gain, dizziness",
        "contraindications": "Type 1 diabetes, diabetic ketoacidosis",
        "guideline_source": "ADA",
    },
    {
        "name": "Empagliflozin",
        "generic_name": "Empagliflozin",
        "drug_class": "SGLT2 Inhibitor",
        "standard_dosage": "10-25 mg orally once daily",
        "side_effects": "Urinary tract infection, dehydration, genital infections",
        "contraindications": "Severe renal impairment",
        "guideline_source": "ADA",
    },
    {
        "name": "Sitagliptin",
        "generic_name": "Sitagliptin",
        "drug_class": "DPP-4 Inhibitor",
        "standard_dosage": "100 mg orally once daily",
        "side_effects": "Headache, nasopharyngitis",
        "contraindications": "Hypersensitivity to sitagliptin",
        "guideline_source": "ADA",
    },
    {
        "name": "Insulin Glargine",
        "generic_name": "Insulin Glargine",
        "drug_class": "Long-acting Insulin",
        "standard_dosage": "Individualized once daily subcutaneous injection",
        "side_effects": "Hypoglycemia, injection site reactions",
        "contraindications": "Hypoglycemia",
        "guideline_source": "ADA",
    },
    {
        "name": "Amlodipine",
        "generic_name": "Amlodipine",
        "drug_class": "Calcium Channel Blocker",
        "standard_dosage": "5-10 mg orally once daily",
        "side_effects": "Peripheral edema, flushing, dizziness",
        "contraindications": "Severe hypotension",
        "guideline_source": "AHA",
    },
    {
        "name": "Losartan",
        "generic_name": "Losartan Potassium",
        "drug_class": "Angiotensin II Receptor Blocker",
        "standard_dosage": "50-100 mg orally once daily",
        "side_effects": "Hyperkalemia, dizziness",
        "contraindications": "Pregnancy",
        "guideline_source": "AHA",
    },
    {
        "name": "Enalapril",
        "generic_name": "Enalapril Maleate",
        "drug_class": "ACE Inhibitor",
        "standard_dosage": "5-20 mg orally once daily",
        "side_effects": "Dry cough, hypotension",
        "contraindications": "History of angioedema",
        "guideline_source": "AHA",
    },
    {
        "name": "Bisoprolol",
        "generic_name": "Bisoprolol",
        "drug_class": "Beta Blocker",
        "standard_dosage": "2.5-10 mg orally once daily",
        "side_effects": "Fatigue, bradycardia",
        "contraindications": "Severe bradycardia",
        "guideline_source": "AHA",
    },
    {
        "name": "Hydrochlorothiazide",
        "generic_name": "Hydrochlorothiazide",
        "drug_class": "Thiazide Diuretic",
        "standard_dosage": "12.5-25 mg orally once daily",
        "side_effects": "Hypokalemia, dehydration",
        "contraindications": "Anuria",
        "guideline_source": "AHA",
    },
    {
        "name": "Atorvastatin",
        "generic_name": "Atorvastatin Calcium",
        "drug_class": "Statin",
        "standard_dosage": "10-80 mg orally once daily",
        "side_effects": "Muscle pain, elevated liver enzymes",
        "contraindications": "Active liver disease",
        "guideline_source": "AHA",
    },
    {
        "name": "Rosuvastatin",
        "generic_name": "Rosuvastatin Calcium",
        "drug_class": "Statin",
        "standard_dosage": "5-40 mg orally once daily",
        "side_effects": "Muscle pain, constipation",
        "contraindications": "Active liver disease",
        "guideline_source": "AHA",
    },
    {
        "name": "Aspirin",
        "generic_name": "Acetylsalicylic Acid",
        "drug_class": "Antiplatelet",
        "standard_dosage": "75-150 mg orally once daily",
        "side_effects": "Gastric irritation, bleeding",
        "contraindications": "Active gastrointestinal bleeding",
        "guideline_source": "AHA",
    },
    {
        "name": "Clopidogrel",
        "generic_name": "Clopidogrel Bisulfate",
        "drug_class": "Antiplatelet",
        "standard_dosage": "75 mg orally once daily",
        "side_effects": "Bleeding, rash",
        "contraindications": "Active pathological bleeding",
        "guideline_source": "AHA",
    },
    {
        "name": "Warfarin",
        "generic_name": "Warfarin Sodium",
        "drug_class": "Anticoagulant",
        "standard_dosage": "2-10 mg orally once daily",
        "side_effects": "Bleeding, bruising",
        "contraindications": "Pregnancy, active bleeding",
        "guideline_source": "CHEST",
    },
    {
        "name": "Apixaban",
        "generic_name": "Apixaban",
        "drug_class": "Direct Oral Anticoagulant",
        "standard_dosage": "5 mg orally twice daily",
        "side_effects": "Bleeding, nausea",
        "contraindications": "Active bleeding",
        "guideline_source": "CHEST",
    },
    {
        "name": "Amoxicillin",
        "generic_name": "Amoxicillin",
        "drug_class": "Penicillin Antibiotic",
        "standard_dosage": "500 mg orally three times daily",
        "side_effects": "Diarrhea, rash",
        "contraindications": "Penicillin allergy",
        "guideline_source": "CDC",
    },
    {
        "name": "Azithromycin",
        "generic_name": "Azithromycin",
        "drug_class": "Macrolide Antibiotic",
        "standard_dosage": "500 mg orally once daily",
        "side_effects": "QT prolongation, diarrhea",
        "contraindications": "Severe liver disease",
        "guideline_source": "CDC",
    },
    {
        "name": "Cefixime",
        "generic_name": "Cefixime",
        "drug_class": "Cephalosporin Antibiotic",
        "standard_dosage": "200-400 mg orally once daily",
        "side_effects": "Nausea, diarrhea",
        "contraindications": "Cephalosporin allergy",
        "guideline_source": "CDC",
    },
    {
        "name": "Ceftriaxone",
        "generic_name": "Ceftriaxone",
        "drug_class": "Cephalosporin Antibiotic",
        "standard_dosage": "1-2 g IV once daily",
        "side_effects": "Injection site pain, diarrhea",
        "contraindications": "Cephalosporin allergy",
        "guideline_source": "CDC",
    },
    {
        "name": "Doxycycline",
        "generic_name": "Doxycycline",
        "drug_class": "Tetracycline Antibiotic",
        "standard_dosage": "100 mg orally twice daily",
        "side_effects": "Photosensitivity, nausea",
        "contraindications": "Pregnancy, children under 8 years",
        "guideline_source": "CDC",
    },
    {
        "name": "Levofloxacin",
        "generic_name": "Levofloxacin",
        "drug_class": "Fluoroquinolone Antibiotic",
        "standard_dosage": "500-750 mg orally once daily",
        "side_effects": "Tendon rupture, dizziness",
        "contraindications": "Myasthenia gravis",
        "guideline_source": "CDC",
    },
    {
        "name": "Clindamycin",
        "generic_name": "Clindamycin",
        "drug_class": "Lincosamide Antibiotic",
        "standard_dosage": "300-450 mg orally every 6 hours",
        "side_effects": "Diarrhea, C. difficile colitis",
        "contraindications": "Hypersensitivity",
        "guideline_source": "CDC",
    },
    {
        "name": "Metronidazole",
        "generic_name": "Metronidazole",
        "drug_class": "Nitroimidazole Antibiotic",
        "standard_dosage": "400-500 mg orally every 8 hours",
        "side_effects": "Metallic taste, nausea",
        "contraindications": "Alcohol use during treatment",
        "guideline_source": "WHO",
    },
    {
        "name": "Vancomycin",
        "generic_name": "Vancomycin",
        "drug_class": "Glycopeptide Antibiotic",
        "standard_dosage": "15-20 mg/kg IV every 8-12 hours",
        "side_effects": "Nephrotoxicity, Red Man syndrome",
        "contraindications": "Hypersensitivity",
        "guideline_source": "IDSA",
    },
    {
        "name": "Meropenem",
        "generic_name": "Meropenem",
        "drug_class": "Carbapenem Antibiotic",
        "standard_dosage": "500 mg-1 g IV every 8 hours",
        "side_effects": "Headache, nausea",
        "contraindications": "Carbapenem allergy",
        "guideline_source": "IDSA",
    },
    {
        "name": "Piperacillin-Tazobactam",
        "generic_name": "Piperacillin + Tazobactam",
        "drug_class": "Beta-lactam/Beta-lactamase Inhibitor",
        "standard_dosage": "4.5 g IV every 6-8 hours",
        "side_effects": "Diarrhea, rash",
        "contraindications": "Penicillin allergy",
        "guideline_source": "IDSA",
    },
    {
        "name": "Linezolid",
        "generic_name": "Linezolid",
        "drug_class": "Oxazolidinone Antibiotic",
        "standard_dosage": "600 mg orally/IV every 12 hours",
        "side_effects": "Bone marrow suppression, headache",
        "contraindications": "Concurrent MAOI therapy",
        "guideline_source": "IDSA",
    },
    {
        "name": "Gentamicin",
        "generic_name": "Gentamicin Sulfate",
        "drug_class": "Aminoglycoside Antibiotic",
        "standard_dosage": "5-7 mg/kg IV once daily",
        "side_effects": "Nephrotoxicity, ototoxicity",
        "contraindications": "Hypersensitivity",
        "guideline_source": "WHO",
    },
    {
        "name": "Trimethoprim-Sulfamethoxazole",
        "generic_name": "Co-trimoxazole",
        "drug_class": "Sulfonamide Antibiotic",
        "standard_dosage": "160/800 mg orally twice daily",
        "side_effects": "Rash, hyperkalemia",
        "contraindications": "Sulfonamide allergy",
        "guideline_source": "CDC",
    },
        {
        "name": "Amikacin",
        "generic_name": "Amikacin Sulfate",
        "drug_class": "Aminoglycoside Antibiotic",
        "standard_dosage": "15 mg/kg IV once daily",
        "side_effects": "Nephrotoxicity, ototoxicity",
        "contraindications": "Hypersensitivity to aminoglycosides",
        "guideline_source": "WHO",
    },
    {
        "name": "Erythromycin",
        "generic_name": "Erythromycin",
        "drug_class": "Macrolide Antibiotic",
        "standard_dosage": "250-500 mg orally every 6 hours",
        "side_effects": "Nausea, diarrhea, QT prolongation",
        "contraindications": "Severe liver disease",
        "guideline_source": "CDC",
    },
    {
        "name": "Flucloxacillin",
        "generic_name": "Flucloxacillin",
        "drug_class": "Penicillin Antibiotic",
        "standard_dosage": "500 mg orally four times daily",
        "side_effects": "Rash, nausea",
        "contraindications": "Penicillin allergy",
        "guideline_source": "NICE",
    },
    {
        "name": "Cloxacillin",
        "generic_name": "Cloxacillin",
        "drug_class": "Penicillin Antibiotic",
        "standard_dosage": "500 mg orally four times daily",
        "side_effects": "Diarrhea, rash",
        "contraindications": "Penicillin allergy",
        "guideline_source": "WHO",
    },
    {
        "name": "Cefuroxime",
        "generic_name": "Cefuroxime",
        "drug_class": "Cephalosporin Antibiotic",
        "standard_dosage": "250-500 mg orally twice daily",
        "side_effects": "Diarrhea, nausea",
        "contraindications": "Cephalosporin allergy",
        "guideline_source": "CDC",
    },
    {
        "name": "Cefepime",
        "generic_name": "Cefepime",
        "drug_class": "Cephalosporin Antibiotic",
        "standard_dosage": "1-2 g IV every 12 hours",
        "side_effects": "Headache, diarrhea",
        "contraindications": "Cephalosporin allergy",
        "guideline_source": "IDSA",
    },
    {
        "name": "Imipenem-Cilastatin",
        "generic_name": "Imipenem + Cilastatin",
        "drug_class": "Carbapenem Antibiotic",
        "standard_dosage": "500 mg IV every 6 hours",
        "side_effects": "Seizures, nausea",
        "contraindications": "Hypersensitivity",
        "guideline_source": "IDSA",
    },
    {
        "name": "Ertapenem",
        "generic_name": "Ertapenem",
        "drug_class": "Carbapenem Antibiotic",
        "standard_dosage": "1 g IV once daily",
        "side_effects": "Diarrhea, headache",
        "contraindications": "Carbapenem allergy",
        "guideline_source": "IDSA",
    },
    {
        "name": "Colistin",
        "generic_name": "Colistimethate Sodium",
        "drug_class": "Polymyxin Antibiotic",
        "standard_dosage": "Weight-based IV dosing",
        "side_effects": "Nephrotoxicity, neurotoxicity",
        "contraindications": "Hypersensitivity",
        "guideline_source": "IDSA",
    },
    {
        "name": "Tigecycline",
        "generic_name": "Tigecycline",
        "drug_class": "Glycylcycline Antibiotic",
        "standard_dosage": "100 mg IV loading then 50 mg every 12 hours",
        "side_effects": "Nausea, vomiting",
        "contraindications": "Hypersensitivity",
        "guideline_source": "IDSA",
    },
    {
        "name": "Fluconazole",
        "generic_name": "Fluconazole",
        "drug_class": "Azole Antifungal",
        "standard_dosage": "150-400 mg orally once daily",
        "side_effects": "Headache, liver enzyme elevation",
        "contraindications": "Hypersensitivity",
        "guideline_source": "IDSA",
    },
    {
        "name": "Itraconazole",
        "generic_name": "Itraconazole",
        "drug_class": "Azole Antifungal",
        "standard_dosage": "200 mg orally once or twice daily",
        "side_effects": "Nausea, edema",
        "contraindications": "Heart failure",
        "guideline_source": "IDSA",
    },
    {
        "name": "Voriconazole",
        "generic_name": "Voriconazole",
        "drug_class": "Azole Antifungal",
        "standard_dosage": "200 mg orally twice daily",
        "side_effects": "Visual disturbances, liver toxicity",
        "contraindications": "Hypersensitivity",
        "guideline_source": "IDSA",
    },
    {
        "name": "Caspofungin",
        "generic_name": "Caspofungin",
        "drug_class": "Echinocandin Antifungal",
        "standard_dosage": "70 mg IV loading then 50 mg daily",
        "side_effects": "Fever, rash",
        "contraindications": "Hypersensitivity",
        "guideline_source": "IDSA",
    },
    {
        "name": "Amphotericin B",
        "generic_name": "Amphotericin B",
        "drug_class": "Polyene Antifungal",
        "standard_dosage": "0.7-1 mg/kg IV daily",
        "side_effects": "Nephrotoxicity, fever, chills",
        "contraindications": "Hypersensitivity",
        "guideline_source": "WHO",
    },
    {
        "name": "Acyclovir",
        "generic_name": "Acyclovir",
        "drug_class": "Antiviral",
        "standard_dosage": "200-800 mg orally five times daily",
        "side_effects": "Headache, nausea",
        "contraindications": "Hypersensitivity",
        "guideline_source": "CDC",
    },
    {
        "name": "Valacyclovir",
        "generic_name": "Valacyclovir",
        "drug_class": "Antiviral",
        "standard_dosage": "500 mg-1 g orally twice daily",
        "side_effects": "Headache, nausea",
        "contraindications": "Hypersensitivity",
        "guideline_source": "CDC",
    },
    {
        "name": "Oseltamivir",
        "generic_name": "Oseltamivir",
        "drug_class": "Antiviral",
        "standard_dosage": "75 mg orally twice daily",
        "side_effects": "Nausea, vomiting",
        "contraindications": "Hypersensitivity",
        "guideline_source": "CDC",
    },
    {
        "name": "Remdesivir",
        "generic_name": "Remdesivir",
        "drug_class": "Antiviral",
        "standard_dosage": "200 mg IV loading then 100 mg daily",
        "side_effects": "Elevated liver enzymes, nausea",
        "contraindications": "Severe hepatic impairment",
        "guideline_source": "WHO",
    },
    {
        "name": "Favipiravir",
        "generic_name": "Favipiravir",
        "drug_class": "Antiviral",
        "standard_dosage": "1800 mg twice daily then 800 mg twice daily",
        "side_effects": "Hyperuricemia, liver enzyme elevation",
        "contraindications": "Pregnancy",
        "guideline_source": "WHO",
    },
    {
        "name": "Ribavirin",
        "generic_name": "Ribavirin",
        "drug_class": "Antiviral",
        "standard_dosage": "Weight-based oral dosing",
        "side_effects": "Hemolytic anemia, fatigue",
        "contraindications": "Pregnancy",
        "guideline_source": "WHO",
    },
    {
        "name": "Tenofovir",
        "generic_name": "Tenofovir Disoproxil Fumarate",
        "drug_class": "Antiretroviral",
        "standard_dosage": "300 mg orally once daily",
        "side_effects": "Renal toxicity, decreased bone density",
        "contraindications": "Severe renal impairment",
        "guideline_source": "WHO",
    },
    {
        "name": "Lamivudine",
        "generic_name": "Lamivudine",
        "drug_class": "Antiretroviral",
        "standard_dosage": "300 mg orally once daily",
        "side_effects": "Headache, fatigue",
        "contraindications": "Hypersensitivity",
        "guideline_source": "WHO",
    },
    {
        "name": "Dolutegravir",
        "generic_name": "Dolutegravir",
        "drug_class": "Integrase Inhibitor",
        "standard_dosage": "50 mg orally once daily",
        "side_effects": "Insomnia, headache",
        "contraindications": "Concurrent dofetilide therapy",
        "guideline_source": "WHO",
    },
    {
        "name": "Efavirenz",
        "generic_name": "Efavirenz",
        "drug_class": "NNRTI",
        "standard_dosage": "600 mg orally once daily",
        "side_effects": "Dizziness, vivid dreams",
        "contraindications": "Hypersensitivity",
        "guideline_source": "WHO",
    },
    {
        "name": "Isoniazid",
        "generic_name": "Isoniazid",
        "drug_class": "Antitubercular",
        "standard_dosage": "300 mg orally once daily",
        "side_effects": "Peripheral neuropathy, hepatotoxicity",
        "contraindications": "Active liver disease",
        "guideline_source": "WHO",
    },
    {
        "name": "Rifampicin",
        "generic_name": "Rifampicin",
        "drug_class": "Antitubercular",
        "standard_dosage": "600 mg orally once daily",
        "side_effects": "Orange body fluids, hepatotoxicity",
        "contraindications": "Severe liver disease",
        "guideline_source": "WHO",
    },
    {
        "name": "Pyrazinamide",
        "generic_name": "Pyrazinamide",
        "drug_class": "Antitubercular",
        "standard_dosage": "20-25 mg/kg orally once daily",
        "side_effects": "Hyperuricemia, hepatotoxicity",
        "contraindications": "Acute gout",
        "guideline_source": "WHO",
    },
    {
        "name": "Ethambutol",
        "generic_name": "Ethambutol",
        "drug_class": "Antitubercular",
        "standard_dosage": "15-20 mg/kg orally once daily",
        "side_effects": "Optic neuritis",
        "contraindications": "Optic neuritis",
        "guideline_source": "WHO",
    },
    {
        "name": "Artemether-Lumefantrine",
        "generic_name": "Artemether + Lumefantrine",
        "drug_class": "Antimalarial",
        "standard_dosage": "Weight-based dosing for 3 days",
        "side_effects": "Headache, dizziness",
        "contraindications": "Hypersensitivity",
        "guideline_source": "WHO",
    },
        {
        "name": "Paracetamol",
        "generic_name": "Acetaminophen",
        "drug_class": "Analgesic/Antipyretic",
        "standard_dosage": "500-1000 mg orally every 4-6 hours (max 4 g/day)",
        "side_effects": "Rare at therapeutic doses; hepatotoxicity in overdose",
        "contraindications": "Severe hepatic impairment",
        "guideline_source": "WHO",
    },
    {
        "name": "Ibuprofen",
        "generic_name": "Ibuprofen",
        "drug_class": "NSAID",
        "standard_dosage": "200-400 mg orally every 6-8 hours",
        "side_effects": "Gastric irritation, renal impairment",
        "contraindications": "Active peptic ulcer disease",
        "guideline_source": "NICE",
    },
    {
        "name": "Diclofenac",
        "generic_name": "Diclofenac Sodium",
        "drug_class": "NSAID",
        "standard_dosage": "50 mg orally two or three times daily",
        "side_effects": "GI bleeding, nausea",
        "contraindications": "Severe heart failure",
        "guideline_source": "NICE",
    },
    {
        "name": "Naproxen",
        "generic_name": "Naproxen",
        "drug_class": "NSAID",
        "standard_dosage": "250-500 mg orally twice daily",
        "side_effects": "Heartburn, dizziness",
        "contraindications": "Active GI bleeding",
        "guideline_source": "NICE",
    },
    {
        "name": "Tramadol",
        "generic_name": "Tramadol Hydrochloride",
        "drug_class": "Opioid Analgesic",
        "standard_dosage": "50-100 mg orally every 4-6 hours",
        "side_effects": "Drowsiness, nausea, constipation",
        "contraindications": "Acute alcohol intoxication",
        "guideline_source": "WHO",
    },
    {
        "name": "Morphine",
        "generic_name": "Morphine Sulfate",
        "drug_class": "Opioid Analgesic",
        "standard_dosage": "5-10 mg orally every 4 hours",
        "side_effects": "Respiratory depression, constipation",
        "contraindications": "Respiratory depression",
        "guideline_source": "WHO",
    },
    {
        "name": "Codeine",
        "generic_name": "Codeine Phosphate",
        "drug_class": "Opioid Analgesic",
        "standard_dosage": "15-60 mg orally every 4-6 hours",
        "side_effects": "Constipation, drowsiness",
        "contraindications": "Children under 12 years",
        "guideline_source": "WHO",
    },
    {
        "name": "Salbutamol",
        "generic_name": "Salbutamol",
        "drug_class": "Short-Acting Beta-2 Agonist",
        "standard_dosage": "100-200 mcg inhaled as needed",
        "side_effects": "Tremor, palpitations",
        "contraindications": "Hypersensitivity",
        "guideline_source": "GINA",
    },
    {
        "name": "Budesonide",
        "generic_name": "Budesonide",
        "drug_class": "Inhaled Corticosteroid",
        "standard_dosage": "200-400 mcg inhaled twice daily",
        "side_effects": "Oral candidiasis, hoarseness",
        "contraindications": "Hypersensitivity",
        "guideline_source": "GINA",
    },
    {
        "name": "Formoterol",
        "generic_name": "Formoterol Fumarate",
        "drug_class": "Long-Acting Beta-2 Agonist",
        "standard_dosage": "12 mcg inhaled twice daily",
        "side_effects": "Palpitations, headache",
        "contraindications": "Hypersensitivity",
        "guideline_source": "GINA",
    },
    {
        "name": "Ipratropium",
        "generic_name": "Ipratropium Bromide",
        "drug_class": "Anticholinergic Bronchodilator",
        "standard_dosage": "2 inhalations four times daily",
        "side_effects": "Dry mouth, cough",
        "contraindications": "Hypersensitivity to atropine derivatives",
        "guideline_source": "GOLD",
    },
    {
        "name": "Prednisolone",
        "generic_name": "Prednisolone",
        "drug_class": "Corticosteroid",
        "standard_dosage": "5-60 mg orally daily",
        "side_effects": "Hyperglycemia, weight gain",
        "contraindications": "Systemic fungal infection",
        "guideline_source": "NICE",
    },
    {
        "name": "Dexamethasone",
        "generic_name": "Dexamethasone",
        "drug_class": "Corticosteroid",
        "standard_dosage": "0.5-10 mg orally daily",
        "side_effects": "Mood changes, hyperglycemia",
        "contraindications": "Untreated systemic infection",
        "guideline_source": "WHO",
    },
    {
        "name": "Omeprazole",
        "generic_name": "Omeprazole",
        "drug_class": "Proton Pump Inhibitor",
        "standard_dosage": "20-40 mg orally once daily",
        "side_effects": "Headache, abdominal pain",
        "contraindications": "Hypersensitivity",
        "guideline_source": "NICE",
    },
    {
        "name": "Pantoprazole",
        "generic_name": "Pantoprazole",
        "drug_class": "Proton Pump Inhibitor",
        "standard_dosage": "40 mg orally once daily",
        "side_effects": "Diarrhea, headache",
        "contraindications": "Hypersensitivity",
        "guideline_source": "NICE",
    },
    {
        "name": "Esomeprazole",
        "generic_name": "Esomeprazole",
        "drug_class": "Proton Pump Inhibitor",
        "standard_dosage": "20-40 mg orally once daily",
        "side_effects": "Constipation, nausea",
        "contraindications": "Hypersensitivity",
        "guideline_source": "NICE",
    },
    {
        "name": "Lactulose",
        "generic_name": "Lactulose",
        "drug_class": "Osmotic Laxative",
        "standard_dosage": "15-30 mL orally daily",
        "side_effects": "Flatulence, diarrhea",
        "contraindications": "Galactosemia",
        "guideline_source": "NICE",
    },
    {
        "name": "Loperamide",
        "generic_name": "Loperamide",
        "drug_class": "Antidiarrheal",
        "standard_dosage": "4 mg initially then 2 mg after each loose stool",
        "side_effects": "Constipation, dizziness",
        "contraindications": "Acute dysentery",
        "guideline_source": "WHO",
    },
    {
        "name": "Ondansetron",
        "generic_name": "Ondansetron",
        "drug_class": "Antiemetic",
        "standard_dosage": "4-8 mg orally every 8 hours",
        "side_effects": "Headache, constipation",
        "contraindications": "Congenital long QT syndrome",
        "guideline_source": "NICE",
    },
    {
        "name": "Domperidone",
        "generic_name": "Domperidone",
        "drug_class": "Prokinetic",
        "standard_dosage": "10 mg orally three times daily",
        "side_effects": "Dry mouth, QT prolongation",
        "contraindications": "Cardiac arrhythmias",
        "guideline_source": "NICE",
    },
    {
        "name": "Levothyroxine",
        "generic_name": "Levothyroxine Sodium",
        "drug_class": "Thyroid Hormone",
        "standard_dosage": "25-100 mcg orally once daily",
        "side_effects": "Palpitations, insomnia",
        "contraindications": "Untreated adrenal insufficiency",
        "guideline_source": "ATA",
    },
    {
        "name": "Methimazole",
        "generic_name": "Methimazole",
        "drug_class": "Antithyroid Drug",
        "standard_dosage": "5-30 mg orally daily",
        "side_effects": "Rash, agranulocytosis",
        "contraindications": "Hypersensitivity",
        "guideline_source": "ATA",
    },
    {
        "name": "Sertraline",
        "generic_name": "Sertraline",
        "drug_class": "SSRI",
        "standard_dosage": "50-200 mg orally once daily",
        "side_effects": "Insomnia, nausea",
        "contraindications": "Concurrent MAOI therapy",
        "guideline_source": "APA",
    },
    {
        "name": "Fluoxetine",
        "generic_name": "Fluoxetine",
        "drug_class": "SSRI",
        "standard_dosage": "20-60 mg orally once daily",
        "side_effects": "Anxiety, insomnia",
        "contraindications": "MAOI use",
        "guideline_source": "APA",
    },
    {
        "name": "Escitalopram",
        "generic_name": "Escitalopram",
        "drug_class": "SSRI",
        "standard_dosage": "10-20 mg orally once daily",
        "side_effects": "Nausea, headache",
        "contraindications": "Concurrent MAOI therapy",
        "guideline_source": "APA",
    },
    {
        "name": "Risperidone",
        "generic_name": "Risperidone",
        "drug_class": "Atypical Antipsychotic",
        "standard_dosage": "2-6 mg orally daily",
        "side_effects": "Weight gain, sedation",
        "contraindications": "Hypersensitivity",
        "guideline_source": "APA",
    },
    {
        "name": "Olanzapine",
        "generic_name": "Olanzapine",
        "drug_class": "Atypical Antipsychotic",
        "standard_dosage": "5-20 mg orally daily",
        "side_effects": "Weight gain, drowsiness",
        "contraindications": "Hypersensitivity",
        "guideline_source": "APA",
    },
    {
        "name": "Haloperidol",
        "generic_name": "Haloperidol",
        "drug_class": "Typical Antipsychotic",
        "standard_dosage": "1-10 mg orally daily",
        "side_effects": "Extrapyramidal symptoms, QT prolongation",
        "contraindications": "Parkinson disease",
        "guideline_source": "APA",
    },
    {
        "name": "Diazepam",
        "generic_name": "Diazepam",
        "drug_class": "Benzodiazepine",
        "standard_dosage": "2-10 mg orally 2-4 times daily",
        "side_effects": "Sedation, dependence",
        "contraindications": "Myasthenia gravis",
        "guideline_source": "APA",
    },
    {
        "name": "Lorazepam",
        "generic_name": "Lorazepam",
        "drug_class": "Benzodiazepine",
        "standard_dosage": "1-4 mg orally daily",
        "side_effects": "Drowsiness, dizziness",
        "contraindications": "Severe respiratory insufficiency",
        "guideline_source": "APA",
    },
        {
        "name": "Carbamazepine",
        "generic_name": "Carbamazepine",
        "drug_class": "Antiepileptic",
        "standard_dosage": "200-400 mg orally twice daily",
        "side_effects": "Dizziness, drowsiness, hyponatremia",
        "contraindications": "Bone marrow depression",
        "guideline_source": "AAN",
    },
    {
        "name": "Sodium Valproate",
        "generic_name": "Valproic Acid",
        "drug_class": "Antiepileptic",
        "standard_dosage": "500-1000 mg orally daily",
        "side_effects": "Weight gain, tremor, hepatotoxicity",
        "contraindications": "Pregnancy, liver disease",
        "guideline_source": "AAN",
    },
    {
        "name": "Levetiracetam",
        "generic_name": "Levetiracetam",
        "drug_class": "Antiepileptic",
        "standard_dosage": "500-1500 mg orally twice daily",
        "side_effects": "Fatigue, irritability",
        "contraindications": "Hypersensitivity",
        "guideline_source": "AAN",
    },
    {
        "name": "Lamotrigine",
        "generic_name": "Lamotrigine",
        "drug_class": "Antiepileptic",
        "standard_dosage": "25-200 mg orally daily",
        "side_effects": "Skin rash, dizziness",
        "contraindications": "Hypersensitivity",
        "guideline_source": "AAN",
    },
    {
        "name": "Gabapentin",
        "generic_name": "Gabapentin",
        "drug_class": "Antiepileptic",
        "standard_dosage": "300-600 mg orally three times daily",
        "side_effects": "Drowsiness, dizziness",
        "contraindications": "Hypersensitivity",
        "guideline_source": "AAN",
    },
    {
        "name": "Pregabalin",
        "generic_name": "Pregabalin",
        "drug_class": "Anticonvulsant",
        "standard_dosage": "75-150 mg orally twice daily",
        "side_effects": "Weight gain, dizziness",
        "contraindications": "Hypersensitivity",
        "guideline_source": "NICE",
    },
    {
        "name": "Phenytoin",
        "generic_name": "Phenytoin Sodium",
        "drug_class": "Antiepileptic",
        "standard_dosage": "300 mg orally daily",
        "side_effects": "Gingival hyperplasia, ataxia",
        "contraindications": "Sinus bradycardia",
        "guideline_source": "AAN",
    },
    {
        "name": "Phenobarbital",
        "generic_name": "Phenobarbital",
        "drug_class": "Barbiturate Antiepileptic",
        "standard_dosage": "60-180 mg orally daily",
        "side_effects": "Sedation, dependence",
        "contraindications": "Porphyria",
        "guideline_source": "WHO",
    },
    {
        "name": "Topiramate",
        "generic_name": "Topiramate",
        "drug_class": "Antiepileptic",
        "standard_dosage": "25-100 mg orally twice daily",
        "side_effects": "Weight loss, cognitive impairment",
        "contraindications": "Metabolic acidosis",
        "guideline_source": "AAN",
    },
    {
        "name": "Pramipexole",
        "generic_name": "Pramipexole",
        "drug_class": "Dopamine Agonist",
        "standard_dosage": "0.125-1.5 mg orally three times daily",
        "side_effects": "Nausea, dizziness",
        "contraindications": "Hypersensitivity",
        "guideline_source": "AAN",
    },
    {
        "name": "Levodopa-Carbidopa",
        "generic_name": "Levodopa + Carbidopa",
        "drug_class": "Antiparkinson Agent",
        "standard_dosage": "100/25 mg orally three times daily",
        "side_effects": "Dyskinesia, nausea",
        "contraindications": "Narrow-angle glaucoma",
        "guideline_source": "AAN",
    },
    {
        "name": "Donepezil",
        "generic_name": "Donepezil",
        "drug_class": "Acetylcholinesterase Inhibitor",
        "standard_dosage": "5-10 mg orally once daily",
        "side_effects": "Nausea, insomnia",
        "contraindications": "Hypersensitivity",
        "guideline_source": "NICE",
    },
    {
        "name": "Memantine",
        "generic_name": "Memantine",
        "drug_class": "NMDA Receptor Antagonist",
        "standard_dosage": "10-20 mg orally daily",
        "side_effects": "Headache, constipation",
        "contraindications": "Hypersensitivity",
        "guideline_source": "NICE",
    },
    {
        "name": "Alendronate",
        "generic_name": "Alendronate Sodium",
        "drug_class": "Bisphosphonate",
        "standard_dosage": "70 mg orally once weekly",
        "side_effects": "Esophagitis, abdominal pain",
        "contraindications": "Esophageal abnormalities",
        "guideline_source": "NOF",
    },
    {
        "name": "Zoledronic Acid",
        "generic_name": "Zoledronic Acid",
        "drug_class": "Bisphosphonate",
        "standard_dosage": "5 mg IV once yearly",
        "side_effects": "Flu-like symptoms, hypocalcemia",
        "contraindications": "Severe renal impairment",
        "guideline_source": "NOF",
    },
    {
        "name": "Allopurinol",
        "generic_name": "Allopurinol",
        "drug_class": "Xanthine Oxidase Inhibitor",
        "standard_dosage": "100-300 mg orally daily",
        "side_effects": "Skin rash, liver dysfunction",
        "contraindications": "Hypersensitivity",
        "guideline_source": "ACR",
    },
    {
        "name": "Febuxostat",
        "generic_name": "Febuxostat",
        "drug_class": "Xanthine Oxidase Inhibitor",
        "standard_dosage": "40-80 mg orally daily",
        "side_effects": "Nausea, elevated liver enzymes",
        "contraindications": "Concurrent azathioprine therapy",
        "guideline_source": "ACR",
    },
    {
        "name": "Tamsulosin",
        "generic_name": "Tamsulosin Hydrochloride",
        "drug_class": "Alpha-1 Blocker",
        "standard_dosage": "0.4 mg orally once daily",
        "side_effects": "Dizziness, orthostatic hypotension",
        "contraindications": "Hypersensitivity",
        "guideline_source": "EAU",
    },
    {
        "name": "Finasteride",
        "generic_name": "Finasteride",
        "drug_class": "5-Alpha Reductase Inhibitor",
        "standard_dosage": "5 mg orally once daily",
        "side_effects": "Reduced libido, erectile dysfunction",
        "contraindications": "Pregnancy",
        "guideline_source": "EAU",
    },
    {
        "name": "Oxybutynin",
        "generic_name": "Oxybutynin Chloride",
        "drug_class": "Anticholinergic",
        "standard_dosage": "5 mg orally two to three times daily",
        "side_effects": "Dry mouth, constipation",
        "contraindications": "Urinary retention",
        "guideline_source": "EAU",
    },
    {
        "name": "Tolterodine",
        "generic_name": "Tolterodine Tartrate",
        "drug_class": "Antimuscarinic",
        "standard_dosage": "2 mg orally twice daily",
        "side_effects": "Dry mouth, blurred vision",
        "contraindications": "Urinary retention",
        "guideline_source": "EAU",
    },
    {
        "name": "Medroxyprogesterone",
        "generic_name": "Medroxyprogesterone Acetate",
        "drug_class": "Progestin",
        "standard_dosage": "10 mg orally daily",
        "side_effects": "Weight gain, irregular bleeding",
        "contraindications": "Active thromboembolic disease",
        "guideline_source": "ACOG",
    },
    {
        "name": "Clomiphene",
        "generic_name": "Clomiphene Citrate",
        "drug_class": "Ovulation Inducer",
        "standard_dosage": "50 mg orally daily for 5 days",
        "side_effects": "Hot flashes, ovarian enlargement",
        "contraindications": "Pregnancy",
        "guideline_source": "ACOG",
    },
    {
        "name": "Ferrous Sulfate",
        "generic_name": "Ferrous Sulfate",
        "drug_class": "Iron Supplement",
        "standard_dosage": "325 mg orally once or twice daily",
        "side_effects": "Constipation, dark stools",
        "contraindications": "Hemochromatosis",
        "guideline_source": "WHO",
    },
    {
        "name": "Calcium Carbonate",
        "generic_name": "Calcium Carbonate",
        "drug_class": "Calcium Supplement",
        "standard_dosage": "500-1000 mg orally daily",
        "side_effects": "Constipation, bloating",
        "contraindications": "Hypercalcemia",
        "guideline_source": "NOF",
    },
    {
        "name": "Cholecalciferol",
        "generic_name": "Vitamin D3",
        "drug_class": "Vitamin Supplement",
        "standard_dosage": "1000-2000 IU orally daily",
        "side_effects": "Hypercalcemia (rare)",
        "contraindications": "Hypervitaminosis D",
        "guideline_source": "Endocrine Society",
    },
    {
        "name": "Cyanocobalamin",
        "generic_name": "Vitamin B12",
        "drug_class": "Vitamin Supplement",
        "standard_dosage": "1000 mcg orally daily",
        "side_effects": "Injection site reactions, rash",
        "contraindications": "Hypersensitivity",
        "guideline_source": "WHO",
    },
    {
        "name": "Folic Acid",
        "generic_name": "Folic Acid",
        "drug_class": "Vitamin Supplement",
        "standard_dosage": "400-1000 mcg orally daily",
        "side_effects": "Rare allergic reactions",
        "contraindications": "Untreated vitamin B12 deficiency",
        "guideline_source": "WHO",
    },
    {
        "name": "Human Papillomavirus Vaccine",
        "generic_name": "HPV Vaccine",
        "drug_class": "Vaccine",
        "standard_dosage": "0.5 mL IM as per vaccination schedule",
        "side_effects": "Injection site pain, fever",
        "contraindications": "Severe allergic reaction to previous dose",
        "guideline_source": "CDC",
    },
    {
        "name": "Pneumococcal Conjugate Vaccine",
        "generic_name": "PCV13",
        "drug_class": "Vaccine",
        "standard_dosage": "0.5 mL IM as per immunization schedule",
        "side_effects": "Injection site pain, mild fever",
        "contraindications": "Severe allergic reaction to vaccine components",
        "guideline_source": "CDC",
    }
    
]

def seed():
    db = SessionLocal()
    try:
        inserted = 0
        for m in medicines:
            existing = db.query(Medicine).filter_by(name=m["name"]).first()
            if not existing:
                db.add(Medicine(**m))
                inserted += 1

        db.commit()
        print(
            f"Seeded {inserted} new medicines "
            f"(skipped {len(medicines) - inserted} duplicates)."
        )

    finally:
        db.close()


if __name__ == "__main__":
    seed()