from app.database.session import SessionLocal
from app.models.lab_reference import LabReference

lab_references = [
    {
        "test_name": "Hemoglobin (Male)",
        "unit": "g/dL",
        "normal_range_min": "13.5",
        "normal_range_max": "17.5",
        "gender_specific": "Male",
        "description": "Measures the oxygen-carrying protein in red blood cells.",
        "guideline_source": "WHO",
    },
    {
        "test_name": "Hemoglobin (Female)",
        "unit": "g/dL",
        "normal_range_min": "12.0",
        "normal_range_max": "15.5",
        "gender_specific": "Female",
        "description": "Measures the oxygen-carrying protein in red blood cells.",
        "guideline_source": "WHO",
    },
    {
        "test_name": "White Blood Cell Count",
        "unit": "×10³/µL",
        "normal_range_min": "4.0",
        "normal_range_max": "11.0",
        "gender_specific": "Both",
        "description": "Measures total white blood cells.",
        "guideline_source": "WHO",
    },
    {
        "test_name": "Red Blood Cell Count (Male)",
        "unit": "million/µL",
        "normal_range_min": "4.7",
        "normal_range_max": "6.1",
        "gender_specific": "Male",
        "description": "Measures total red blood cells.",
        "guideline_source": "WHO",
    },
    {
        "test_name": "Red Blood Cell Count (Female)",
        "unit": "million/µL",
        "normal_range_min": "4.2",
        "normal_range_max": "5.4",
        "gender_specific": "Female",
        "description": "Measures total red blood cells.",
        "guideline_source": "WHO",
    },
    {
        "test_name": "Platelet Count",
        "unit": "×10³/µL",
        "normal_range_min": "150",
        "normal_range_max": "450",
        "gender_specific": "Both",
        "description": "Measures platelets responsible for blood clotting.",
        "guideline_source": "WHO",
    },
    {
        "test_name": "Hematocrit (Male)",
        "unit": "%",
        "normal_range_min": "41",
        "normal_range_max": "53",
        "gender_specific": "Male",
        "description": "Percentage of red blood cells in blood.",
        "guideline_source": "WHO",
    },
    {
        "test_name": "Hematocrit (Female)",
        "unit": "%",
        "normal_range_min": "36",
        "normal_range_max": "46",
        "gender_specific": "Female",
        "description": "Percentage of red blood cells in blood.",
        "guideline_source": "WHO",
    },
    {
        "test_name": "Mean Corpuscular Volume",
        "unit": "fL",
        "normal_range_min": "80",
        "normal_range_max": "100",
        "gender_specific": "Both",
        "description": "Average size of red blood cells.",
        "guideline_source": "WHO",
    },
    {
        "test_name": "Mean Corpuscular Hemoglobin",
        "unit": "pg",
        "normal_range_min": "27",
        "normal_range_max": "33",
        "gender_specific": "Both",
        "description": "Average amount of hemoglobin per red blood cell.",
        "guideline_source": "WHO",
    },
    {
        "test_name": "Mean Corpuscular Hemoglobin Concentration",
        "unit": "g/dL",
        "normal_range_min": "32",
        "normal_range_max": "36",
        "gender_specific": "Both",
        "description": "Average concentration of hemoglobin in red blood cells.",
        "guideline_source": "WHO",
    },
    {
        "test_name": "Red Cell Distribution Width",
        "unit": "%",
        "normal_range_min": "11.5",
        "normal_range_max": "14.5",
        "gender_specific": "Both",
        "description": "Measures variation in red blood cell size.",
        "guideline_source": "WHO",
    },
    {
        "test_name": "Neutrophils",
        "unit": "%",
        "normal_range_min": "40",
        "normal_range_max": "70",
        "gender_specific": "Both",
        "description": "Percentage of neutrophils in white blood cells.",
        "guideline_source": "WHO",
    },
    {
        "test_name": "Lymphocytes",
        "unit": "%",
        "normal_range_min": "20",
        "normal_range_max": "40",
        "gender_specific": "Both",
        "description": "Percentage of lymphocytes in white blood cells.",
        "guideline_source": "WHO",
    },
    {
        "test_name": "Monocytes",
        "unit": "%",
        "normal_range_min": "2",
        "normal_range_max": "8",
        "gender_specific": "Both",
        "description": "Percentage of monocytes in white blood cells.",
        "guideline_source": "WHO",
    },
    {
        "test_name": "Eosinophils",
        "unit": "%",
        "normal_range_min": "1",
        "normal_range_max": "6",
        "gender_specific": "Both",
        "description": "Percentage of eosinophils in white blood cells.",
        "guideline_source": "WHO",
    },
    {
        "test_name": "Basophils",
        "unit": "%",
        "normal_range_min": "0",
        "normal_range_max": "2",
        "gender_specific": "Both",
        "description": "Percentage of basophils in white blood cells.",
        "guideline_source": "WHO",
    },
    {
        "test_name": "Erythrocyte Sedimentation Rate (Male)",
        "unit": "mm/hr",
        "normal_range_min": "0",
        "normal_range_max": "15",
        "gender_specific": "Male",
        "description": "Measures inflammation.",
        "guideline_source": "WHO",
    },
    {
        "test_name": "Erythrocyte Sedimentation Rate (Female)",
        "unit": "mm/hr",
        "normal_range_min": "0",
        "normal_range_max": "20",
        "gender_specific": "Female",
        "description": "Measures inflammation.",
        "guideline_source": "WHO",
    },
    {
        "test_name": "C-Reactive Protein",
        "unit": "mg/L",
        "normal_range_min": "0",
        "normal_range_max": "5",
        "gender_specific": "Both",
        "description": "Marker of acute inflammation.",
        "guideline_source": "WHO",
    },
    {
        "test_name": "Procalcitonin",
        "unit": "ng/mL",
        "normal_range_min": "0",
        "normal_range_max": "0.05",
        "gender_specific": "Both",
        "description": "Marker for bacterial infection.",
        "guideline_source": "WHO",
    },
    {
        "test_name": "Ferritin (Male)",
        "unit": "ng/mL",
        "normal_range_min": "30",
        "normal_range_max": "400",
        "gender_specific": "Male",
        "description": "Measures iron stores.",
        "guideline_source": "WHO",
    },
    {
        "test_name": "Ferritin (Female)",
        "unit": "ng/mL",
        "normal_range_min": "15",
        "normal_range_max": "150",
        "gender_specific": "Female",
        "description": "Measures iron stores.",
        "guideline_source": "WHO",
    },
    {
        "test_name": "Serum Iron",
        "unit": "µg/dL",
        "normal_range_min": "60",
        "normal_range_max": "170",
        "gender_specific": "Both",
        "description": "Measures circulating iron.",
        "guideline_source": "WHO",
    },
    {
        "test_name": "Total Iron Binding Capacity",
        "unit": "µg/dL",
        "normal_range_min": "240",
        "normal_range_max": "450",
        "gender_specific": "Both",
        "description": "Measures blood's capacity to bind iron.",
        "guideline_source": "WHO",
    },
    {
        "test_name": "Transferrin Saturation",
        "unit": "%",
        "normal_range_min": "20",
        "normal_range_max": "50",
        "gender_specific": "Both",
        "description": "Measures iron transport saturation.",
        "guideline_source": "WHO",
    },
    {
        "test_name": "Reticulocyte Count",
        "unit": "%",
        "normal_range_min": "0.5",
        "normal_range_max": "2.5",
        "gender_specific": "Both",
        "description": "Measures immature red blood cells.",
        "guideline_source": "WHO",
    },
    {
        "test_name": "Absolute Neutrophil Count",
        "unit": "/µL",
        "normal_range_min": "1500",
        "normal_range_max": "8000",
        "gender_specific": "Both",
        "description": "Measures neutrophil count.",
        "guideline_source": "WHO",
    },
    {
        "test_name": "Absolute Lymphocyte Count",
        "unit": "/µL",
        "normal_range_min": "1000",
        "normal_range_max": "4800",
        "gender_specific": "Both",
        "description": "Measures lymphocyte count.",
        "guideline_source": "WHO",
    },
    {
        "test_name": "Absolute Monocyte Count",
        "unit": "/µL",
        "normal_range_min": "200",
        "normal_range_max": "800",
        "gender_specific": "Both",
        "description": "Measures monocyte count.",
        "guideline_source": "WHO",
    },
        {
        "test_name": "Blood Urea Nitrogen",
        "unit": "mg/dL",
        "normal_range_min": "7",
        "normal_range_max": "20",
        "gender_specific": "Both",
        "description": "Measures urea nitrogen to assess kidney function.",
        "guideline_source": "KDIGO",
    },
    {
        "test_name": "Serum Creatinine (Male)",
        "unit": "mg/dL",
        "normal_range_min": "0.74",
        "normal_range_max": "1.35",
        "gender_specific": "Male",
        "description": "Measures kidney function.",
        "guideline_source": "KDIGO",
    },
    {
        "test_name": "Serum Creatinine (Female)",
        "unit": "mg/dL",
        "normal_range_min": "0.59",
        "normal_range_max": "1.04",
        "gender_specific": "Female",
        "description": "Measures kidney function.",
        "guideline_source": "KDIGO",
    },
    {
        "test_name": "Estimated GFR",
        "unit": "mL/min/1.73m²",
        "normal_range_min": "90",
        "normal_range_max": "120",
        "gender_specific": "Both",
        "description": "Estimates kidney filtration rate.",
        "guideline_source": "KDIGO",
    },
    {
        "test_name": "Serum Sodium",
        "unit": "mmol/L",
        "normal_range_min": "135",
        "normal_range_max": "145",
        "gender_specific": "Both",
        "description": "Measures sodium concentration.",
        "guideline_source": "KDIGO",
    },
    {
        "test_name": "Serum Potassium",
        "unit": "mmol/L",
        "normal_range_min": "3.5",
        "normal_range_max": "5.1",
        "gender_specific": "Both",
        "description": "Measures potassium concentration.",
        "guideline_source": "KDIGO",
    },
    {
        "test_name": "Serum Chloride",
        "unit": "mmol/L",
        "normal_range_min": "98",
        "normal_range_max": "107",
        "gender_specific": "Both",
        "description": "Measures chloride concentration.",
        "guideline_source": "KDIGO",
    },
    {
        "test_name": "Serum Bicarbonate",
        "unit": "mmol/L",
        "normal_range_min": "22",
        "normal_range_max": "29",
        "gender_specific": "Both",
        "description": "Measures bicarbonate level for acid-base balance.",
        "guideline_source": "KDIGO",
    },
    {
        "test_name": "Serum Calcium",
        "unit": "mg/dL",
        "normal_range_min": "8.5",
        "normal_range_max": "10.5",
        "gender_specific": "Both",
        "description": "Measures blood calcium level.",
        "guideline_source": "Endocrine Society",
    },
    {
        "test_name": "Ionized Calcium",
        "unit": "mmol/L",
        "normal_range_min": "1.12",
        "normal_range_max": "1.32",
        "gender_specific": "Both",
        "description": "Measures biologically active calcium.",
        "guideline_source": "Endocrine Society",
    },
    {
        "test_name": "Serum Magnesium",
        "unit": "mg/dL",
        "normal_range_min": "1.7",
        "normal_range_max": "2.2",
        "gender_specific": "Both",
        "description": "Measures magnesium level.",
        "guideline_source": "WHO",
    },
    {
        "test_name": "Serum Phosphorus",
        "unit": "mg/dL",
        "normal_range_min": "2.5",
        "normal_range_max": "4.5",
        "gender_specific": "Both",
        "description": "Measures phosphorus level.",
        "guideline_source": "KDIGO",
    },
    {
        "test_name": "Uric Acid (Male)",
        "unit": "mg/dL",
        "normal_range_min": "3.4",
        "normal_range_max": "7.0",
        "gender_specific": "Male",
        "description": "Measures uric acid level.",
        "guideline_source": "ACR",
    },
    {
        "test_name": "Uric Acid (Female)",
        "unit": "mg/dL",
        "normal_range_min": "2.4",
        "normal_range_max": "6.0",
        "gender_specific": "Female",
        "description": "Measures uric acid level.",
        "guideline_source": "ACR",
    },
    {
        "test_name": "Fasting Blood Glucose",
        "unit": "mg/dL",
        "normal_range_min": "70",
        "normal_range_max": "99",
        "gender_specific": "Both",
        "description": "Measures fasting blood sugar.",
        "guideline_source": "ADA",
    },
    {
        "test_name": "Random Blood Glucose",
        "unit": "mg/dL",
        "normal_range_min": "70",
        "normal_range_max": "140",
        "gender_specific": "Both",
        "description": "Measures blood glucose at any time.",
        "guideline_source": "ADA",
    },
    {
        "test_name": "HbA1c",
        "unit": "%",
        "normal_range_min": "4.0",
        "normal_range_max": "5.6",
        "gender_specific": "Both",
        "description": "Measures average blood glucose over 3 months.",
        "guideline_source": "ADA",
    },
    {
        "test_name": "Oral Glucose Tolerance Test",
        "unit": "mg/dL",
        "normal_range_min": "70",
        "normal_range_max": "139",
        "gender_specific": "Both",
        "description": "Measures glucose metabolism after glucose load.",
        "guideline_source": "ADA",
    },
    {
        "test_name": "Serum Insulin",
        "unit": "µIU/mL",
        "normal_range_min": "2",
        "normal_range_max": "25",
        "gender_specific": "Both",
        "description": "Measures circulating insulin.",
        "guideline_source": "ADA",
    },
    {
        "test_name": "C-Peptide",
        "unit": "ng/mL",
        "normal_range_min": "0.5",
        "normal_range_max": "2.0",
        "gender_specific": "Both",
        "description": "Measures endogenous insulin production.",
        "guideline_source": "ADA",
    },
    {
        "test_name": "Total Cholesterol",
        "unit": "mg/dL",
        "normal_range_min": "125",
        "normal_range_max": "200",
        "gender_specific": "Both",
        "description": "Measures total blood cholesterol.",
        "guideline_source": "AHA",
    },
    {
        "test_name": "HDL Cholesterol",
        "unit": "mg/dL",
        "normal_range_min": "40",
        "normal_range_max": "100",
        "gender_specific": "Both",
        "description": "Measures high-density lipoprotein cholesterol.",
        "guideline_source": "AHA",
    },
    {
        "test_name": "LDL Cholesterol",
        "unit": "mg/dL",
        "normal_range_min": "0",
        "normal_range_max": "100",
        "gender_specific": "Both",
        "description": "Measures low-density lipoprotein cholesterol.",
        "guideline_source": "AHA",
    },
    {
        "test_name": "Triglycerides",
        "unit": "mg/dL",
        "normal_range_min": "0",
        "normal_range_max": "150",
        "gender_specific": "Both",
        "description": "Measures blood triglycerides.",
        "guideline_source": "AHA",
    },
    {
        "test_name": "Very Low Density Lipoprotein",
        "unit": "mg/dL",
        "normal_range_min": "5",
        "normal_range_max": "40",
        "gender_specific": "Both",
        "description": "Measures VLDL cholesterol.",
        "guideline_source": "AHA",
    },
    {
        "test_name": "Total Bilirubin",
        "unit": "mg/dL",
        "normal_range_min": "0.2",
        "normal_range_max": "1.2",
        "gender_specific": "Both",
        "description": "Measures total bilirubin level.",
        "guideline_source": "AASLD",
    },
    {
        "test_name": "Direct Bilirubin",
        "unit": "mg/dL",
        "normal_range_min": "0.0",
        "normal_range_max": "0.3",
        "gender_specific": "Both",
        "description": "Measures conjugated bilirubin.",
        "guideline_source": "AASLD",
    },
    {
        "test_name": "Indirect Bilirubin",
        "unit": "mg/dL",
        "normal_range_min": "0.2",
        "normal_range_max": "0.9",
        "gender_specific": "Both",
        "description": "Measures unconjugated bilirubin.",
        "guideline_source": "AASLD",
    },
    {
        "test_name": "Alanine Aminotransferase",
        "unit": "U/L",
        "normal_range_min": "7",
        "normal_range_max": "56",
        "gender_specific": "Both",
        "description": "Measures liver enzyme ALT.",
        "guideline_source": "AASLD",
    },
    {
        "test_name": "Aspartate Aminotransferase",
        "unit": "U/L",
        "normal_range_min": "10",
        "normal_range_max": "40",
        "gender_specific": "Both",
        "description": "Measures liver enzyme AST.",
        "guideline_source": "AASLD",
    },
        {
        "test_name": "Alkaline Phosphatase",
        "unit": "U/L",
        "normal_range_min": "44",
        "normal_range_max": "147",
        "gender_specific": "Both",
        "description": "Measures alkaline phosphatase enzyme activity.",
        "guideline_source": "AASLD",
    },
    {
        "test_name": "Gamma Glutamyl Transferase",
        "unit": "U/L",
        "normal_range_min": "9",
        "normal_range_max": "48",
        "gender_specific": "Both",
        "description": "Measures GGT enzyme associated with liver and bile ducts.",
        "guideline_source": "AASLD",
    },
    {
        "test_name": "Total Protein",
        "unit": "g/dL",
        "normal_range_min": "6.0",
        "normal_range_max": "8.3",
        "gender_specific": "Both",
        "description": "Measures total protein in blood.",
        "guideline_source": "AASLD",
    },
    {
        "test_name": "Albumin",
        "unit": "g/dL",
        "normal_range_min": "3.5",
        "normal_range_max": "5.0",
        "gender_specific": "Both",
        "description": "Measures albumin produced by the liver.",
        "guideline_source": "AASLD",
    },
    {
        "test_name": "Globulin",
        "unit": "g/dL",
        "normal_range_min": "2.0",
        "normal_range_max": "3.5",
        "gender_specific": "Both",
        "description": "Measures globulin proteins in blood.",
        "guideline_source": "AASLD",
    },
    {
        "test_name": "Albumin Globulin Ratio",
        "unit": "Ratio",
        "normal_range_min": "1.0",
        "normal_range_max": "2.2",
        "gender_specific": "Both",
        "description": "Measures albumin to globulin ratio.",
        "guideline_source": "AASLD",
    },
    {
        "test_name": "Thyroid Stimulating Hormone",
        "unit": "mIU/L",
        "normal_range_min": "0.4",
        "normal_range_max": "4.0",
        "gender_specific": "Both",
        "description": "Measures thyroid stimulating hormone.",
        "guideline_source": "ATA",
    },
    {
        "test_name": "Free T3",
        "unit": "pg/mL",
        "normal_range_min": "2.3",
        "normal_range_max": "4.2",
        "gender_specific": "Both",
        "description": "Measures free triiodothyronine.",
        "guideline_source": "ATA",
    },
    {
        "test_name": "Free T4",
        "unit": "ng/dL",
        "normal_range_min": "0.8",
        "normal_range_max": "1.8",
        "gender_specific": "Both",
        "description": "Measures free thyroxine.",
        "guideline_source": "ATA",
    },
    {
        "test_name": "Total T3",
        "unit": "ng/dL",
        "normal_range_min": "80",
        "normal_range_max": "200",
        "gender_specific": "Both",
        "description": "Measures total triiodothyronine.",
        "guideline_source": "ATA",
    },
    {
        "test_name": "Total T4",
        "unit": "µg/dL",
        "normal_range_min": "5.0",
        "normal_range_max": "12.0",
        "gender_specific": "Both",
        "description": "Measures total thyroxine.",
        "guideline_source": "ATA",
    },
    {
        "test_name": "Troponin I",
        "unit": "ng/mL",
        "normal_range_min": "0.00",
        "normal_range_max": "0.04",
        "gender_specific": "Both",
        "description": "Cardiac marker for myocardial injury.",
        "guideline_source": "AHA",
    },
    {
        "test_name": "Troponin T",
        "unit": "ng/mL",
        "normal_range_min": "0.00",
        "normal_range_max": "0.01",
        "gender_specific": "Both",
        "description": "Cardiac marker indicating heart muscle damage.",
        "guideline_source": "AHA",
    },
    {
        "test_name": "Creatine Kinase MB",
        "unit": "ng/mL",
        "normal_range_min": "0",
        "normal_range_max": "5",
        "gender_specific": "Both",
        "description": "Measures CK-MB enzyme in heart muscle.",
        "guideline_source": "AHA",
    },
    {
        "test_name": "B-Type Natriuretic Peptide",
        "unit": "pg/mL",
        "normal_range_min": "0",
        "normal_range_max": "100",
        "gender_specific": "Both",
        "description": "Marker used in heart failure diagnosis.",
        "guideline_source": "AHA",
    },
    {
        "test_name": "Prothrombin Time",
        "unit": "seconds",
        "normal_range_min": "11",
        "normal_range_max": "13.5",
        "gender_specific": "Both",
        "description": "Measures blood clotting time.",
        "guideline_source": "ISTH",
    },
    {
        "test_name": "International Normalized Ratio",
        "unit": "INR",
        "normal_range_min": "0.8",
        "normal_range_max": "1.2",
        "gender_specific": "Both",
        "description": "Standardized measure of blood clotting.",
        "guideline_source": "ISTH",
    },
    {
        "test_name": "Activated Partial Thromboplastin Time",
        "unit": "seconds",
        "normal_range_min": "25",
        "normal_range_max": "35",
        "gender_specific": "Both",
        "description": "Measures intrinsic coagulation pathway.",
        "guideline_source": "ISTH",
    },
    {
        "test_name": "Fibrinogen",
        "unit": "mg/dL",
        "normal_range_min": "200",
        "normal_range_max": "400",
        "gender_specific": "Both",
        "description": "Measures clotting protein fibrinogen.",
        "guideline_source": "ISTH",
    },
    {
        "test_name": "D-Dimer",
        "unit": "µg/mL",
        "normal_range_min": "0",
        "normal_range_max": "0.5",
        "gender_specific": "Both",
        "description": "Measures fibrin degradation products.",
        "guideline_source": "ISTH",
    },
    {
        "test_name": "Urine pH",
        "unit": "pH",
        "normal_range_min": "4.5",
        "normal_range_max": "8.0",
        "gender_specific": "Both",
        "description": "Measures acidity of urine.",
        "guideline_source": "KDIGO",
    },
    {
        "test_name": "Urine Specific Gravity",
        "unit": "",
        "normal_range_min": "1.005",
        "normal_range_max": "1.030",
        "gender_specific": "Both",
        "description": "Measures urine concentration.",
        "guideline_source": "KDIGO",
    },
    {
        "test_name": "Urine Protein",
        "unit": "mg/dL",
        "normal_range_min": "0",
        "normal_range_max": "20",
        "gender_specific": "Both",
        "description": "Measures protein in urine.",
        "guideline_source": "KDIGO",
    },
    {
        "test_name": "Urine Glucose",
        "unit": "mg/dL",
        "normal_range_min": "0",
        "normal_range_max": "15",
        "gender_specific": "Both",
        "description": "Measures glucose in urine.",
        "guideline_source": "ADA",
    },
    {
        "test_name": "Urine Ketones",
        "unit": "mg/dL",
        "normal_range_min": "0",
        "normal_range_max": "5",
        "gender_specific": "Both",
        "description": "Measures ketone bodies in urine.",
        "guideline_source": "ADA",
    },
    {
        "test_name": "Urine Microalbumin",
        "unit": "mg/L",
        "normal_range_min": "0",
        "normal_range_max": "30",
        "gender_specific": "Both",
        "description": "Detects early kidney damage.",
        "guideline_source": "KDIGO",
    },
    {
        "test_name": "Serum Amylase",
        "unit": "U/L",
        "normal_range_min": "30",
        "normal_range_max": "110",
        "gender_specific": "Both",
        "description": "Measures pancreatic enzyme amylase.",
        "guideline_source": "ACG",
    },
    {
        "test_name": "Serum Lipase",
        "unit": "U/L",
        "normal_range_min": "13",
        "normal_range_max": "60",
        "gender_specific": "Both",
        "description": "Measures pancreatic enzyme lipase.",
        "guideline_source": "ACG",
    },
    {
        "test_name": "Lactate Dehydrogenase",
        "unit": "U/L",
        "normal_range_min": "140",
        "normal_range_max": "280",
        "gender_specific": "Both",
        "description": "Measures LDH enzyme released during tissue damage.",
        "guideline_source": "WHO",
    },
    {
        "test_name": "Serum Osmolality",
        "unit": "mOsm/kg",
        "normal_range_min": "275",
        "normal_range_max": "295",
        "gender_specific": "Both",
        "description": "Measures concentration of dissolved particles in blood.",
        "guideline_source": "KDIGO",
    },
        {
        "test_name": "Arterial Blood pH",
        "unit": "pH",
        "normal_range_min": "7.35",
        "normal_range_max": "7.45",
        "gender_specific": "Both",
        "description": "Measures arterial blood acidity.",
        "guideline_source": "ATS",
    },
    {
        "test_name": "Arterial pO2",
        "unit": "mmHg",
        "normal_range_min": "80",
        "normal_range_max": "100",
        "gender_specific": "Both",
        "description": "Measures arterial oxygen pressure.",
        "guideline_source": "ATS",
    },
    {
        "test_name": "Arterial pCO2",
        "unit": "mmHg",
        "normal_range_min": "35",
        "normal_range_max": "45",
        "gender_specific": "Both",
        "description": "Measures arterial carbon dioxide pressure.",
        "guideline_source": "ATS",
    },
    {
        "test_name": "Arterial Oxygen Saturation",
        "unit": "%",
        "normal_range_min": "95",
        "normal_range_max": "100",
        "gender_specific": "Both",
        "description": "Measures oxygen saturation in arterial blood.",
        "guideline_source": "ATS",
    },
    {
        "test_name": "Lactic Acid",
        "unit": "mmol/L",
        "normal_range_min": "0.5",
        "normal_range_max": "2.2",
        "gender_specific": "Both",
        "description": "Measures blood lactate concentration.",
        "guideline_source": "WHO",
    },
    {
        "test_name": "Vitamin B12",
        "unit": "pg/mL",
        "normal_range_min": "200",
        "normal_range_max": "900",
        "gender_specific": "Both",
        "description": "Measures vitamin B12 levels.",
        "guideline_source": "WHO",
    },
    {
        "test_name": "Vitamin D",
        "unit": "ng/mL",
        "normal_range_min": "30",
        "normal_range_max": "100",
        "gender_specific": "Both",
        "description": "Measures vitamin D status.",
        "guideline_source": "Endocrine Society",
    },
    {
        "test_name": "Folate",
        "unit": "ng/mL",
        "normal_range_min": "3",
        "normal_range_max": "20",
        "gender_specific": "Both",
        "description": "Measures folate concentration.",
        "guideline_source": "WHO",
    },
    {
        "test_name": "Parathyroid Hormone",
        "unit": "pg/mL",
        "normal_range_min": "10",
        "normal_range_max": "65",
        "gender_specific": "Both",
        "description": "Measures parathyroid hormone level.",
        "guideline_source": "Endocrine Society",
    },
    {
        "test_name": "Cortisol Morning",
        "unit": "µg/dL",
        "normal_range_min": "5",
        "normal_range_max": "25",
        "gender_specific": "Both",
        "description": "Measures morning cortisol level.",
        "guideline_source": "Endocrine Society",
    },
    {
        "test_name": "Adrenocorticotropic Hormone",
        "unit": "pg/mL",
        "normal_range_min": "10",
        "normal_range_max": "60",
        "gender_specific": "Both",
        "description": "Measures ACTH concentration.",
        "guideline_source": "Endocrine Society",
    },
    {
        "test_name": "Prolactin",
        "unit": "ng/mL",
        "normal_range_min": "4",
        "normal_range_max": "23",
        "gender_specific": "Both",
        "description": "Measures prolactin hormone.",
        "guideline_source": "Endocrine Society",
    },
    {
        "test_name": "Luteinizing Hormone",
        "unit": "IU/L",
        "normal_range_min": "1",
        "normal_range_max": "20",
        "gender_specific": "Both",
        "description": "Measures luteinizing hormone.",
        "guideline_source": "Endocrine Society",
    },
    {
        "test_name": "Follicle Stimulating Hormone",
        "unit": "IU/L",
        "normal_range_min": "1",
        "normal_range_max": "12",
        "gender_specific": "Both",
        "description": "Measures follicle stimulating hormone.",
        "guideline_source": "Endocrine Society",
    },
    {
        "test_name": "Testosterone (Male)",
        "unit": "ng/dL",
        "normal_range_min": "300",
        "normal_range_max": "1000",
        "gender_specific": "Male",
        "description": "Measures serum testosterone in males.",
        "guideline_source": "Endocrine Society",
    },
    {
        "test_name": "Testosterone (Female)",
        "unit": "ng/dL",
        "normal_range_min": "15",
        "normal_range_max": "70",
        "gender_specific": "Female",
        "description": "Measures serum testosterone in females.",
        "guideline_source": "Endocrine Society",
    },
    {
        "test_name": "Estradiol",
        "unit": "pg/mL",
        "normal_range_min": "15",
        "normal_range_max": "350",
        "gender_specific": "Female",
        "description": "Measures estradiol hormone.",
        "guideline_source": "Endocrine Society",
    },
    {
        "test_name": "Progesterone",
        "unit": "ng/mL",
        "normal_range_min": "0.1",
        "normal_range_max": "25",
        "gender_specific": "Female",
        "description": "Measures progesterone hormone.",
        "guideline_source": "Endocrine Society",
    },
    {
        "test_name": "Prostate Specific Antigen",
        "unit": "ng/mL",
        "normal_range_min": "0",
        "normal_range_max": "4",
        "gender_specific": "Male",
        "description": "Measures PSA for prostate evaluation.",
        "guideline_source": "AUA",
    },
    {
        "test_name": "CA-125",
        "unit": "U/mL",
        "normal_range_min": "0",
        "normal_range_max": "35",
        "gender_specific": "Female",
        "description": "Tumor marker associated with ovarian cancer.",
        "guideline_source": "NCCN",
    },
    {
        "test_name": "Carcinoembryonic Antigen",
        "unit": "ng/mL",
        "normal_range_min": "0",
        "normal_range_max": "3",
        "gender_specific": "Both",
        "description": "Tumor marker used in colorectal and other cancers.",
        "guideline_source": "NCCN",
    },
    {
        "test_name": "Alpha Fetoprotein",
        "unit": "ng/mL",
        "normal_range_min": "0",
        "normal_range_max": "10",
        "gender_specific": "Both",
        "description": "Tumor marker for liver and germ cell tumors.",
        "guideline_source": "NCCN",
    },
    {
        "test_name": "CA 19-9",
        "unit": "U/mL",
        "normal_range_min": "0",
        "normal_range_max": "37",
        "gender_specific": "Both",
        "description": "Tumor marker associated with pancreatic cancer.",
        "guideline_source": "NCCN",
    },
    {
        "test_name": "Beta hCG",
        "unit": "mIU/mL",
        "normal_range_min": "0",
        "normal_range_max": "5",
        "gender_specific": "Both",
        "description": "Measures human chorionic gonadotropin.",
        "guideline_source": "ACOG",
    },
    {
        "test_name": "Rheumatoid Factor",
        "unit": "IU/mL",
        "normal_range_min": "0",
        "normal_range_max": "14",
        "gender_specific": "Both",
        "description": "Autoantibody used in rheumatoid arthritis diagnosis.",
        "guideline_source": "ACR",
    },
    {
        "test_name": "Anti Cyclic Citrullinated Peptide Antibody",
        "unit": "U/mL",
        "normal_range_min": "0",
        "normal_range_max": "20",
        "gender_specific": "Both",
        "description": "Highly specific marker for rheumatoid arthritis.",
        "guideline_source": "ACR",
    },
    {
        "test_name": "Antinuclear Antibody",
        "unit": "Titer",
        "normal_range_min": "Negative",
        "normal_range_max": "Negative",
        "gender_specific": "Both",
        "description": "Screening test for autoimmune diseases.",
        "guideline_source": "ACR",
    },
    {
        "test_name": "Complement C3",
        "unit": "mg/dL",
        "normal_range_min": "90",
        "normal_range_max": "180",
        "gender_specific": "Both",
        "description": "Measures complement C3 protein.",
        "guideline_source": "ACR",
    },
    {
        "test_name": "Complement C4",
        "unit": "mg/dL",
        "normal_range_min": "10",
        "normal_range_max": "40",
        "gender_specific": "Both",
        "description": "Measures complement C4 protein.",
        "guideline_source": "ACR",
    },
    {
        "test_name": "Anti Double Stranded DNA Antibody",
        "unit": "IU/mL",
        "normal_range_min": "0",
        "normal_range_max": "30",
        "gender_specific": "Both",
        "description": "Autoantibody used in systemic lupus erythematosus diagnosis.",
        "guideline_source": "ACR",
    },
]

def seed():
    db = SessionLocal()
    try:
        inserted = 0
        for l in lab_references:
            existing = db.query(LabReference).filter_by(test_name=l["test_name"]).first()
            if not existing:
                db.add(LabReference(**l))
                inserted += 1

        db.commit()
        print(
            f"Seeded {inserted} new lab references "
            f"(skipped {len(lab_references) - inserted} duplicates)."
        )

    finally:
        db.close()


if __name__ == "__main__":
    seed()