from app.database.session import SessionLocal
from app.models.disease import Disease

diseases = [
    {
        "name": "Type 2 Diabetes Mellitus",
        "category": "Endocrinology",
        "description": "A chronic metabolic disorder characterized by insulin resistance and elevated blood glucose levels.",
        "common_symptoms": "Frequent urination, excessive thirst, fatigue, blurred vision",
        "severity_level": "Moderate",
        "guideline_source": "ADA",
    },
    {
        "name": "Type 1 Diabetes Mellitus",
        "category": "Endocrinology",
        "description": "An autoimmune disease resulting in destruction of pancreatic beta cells.",
        "common_symptoms": "Weight loss, excessive thirst, fatigue, frequent urination",
        "severity_level": "Severe",
        "guideline_source": "ADA",
    },
    {
        "name": "Essential Hypertension",
        "category": "Cardiology",
        "description": "Persistent elevation of arterial blood pressure without an identifiable secondary cause.",
        "common_symptoms": "Headache, dizziness, blurred vision",
        "severity_level": "Moderate",
        "guideline_source": "AHA",
    },
    {
        "name": "Coronary Artery Disease",
        "category": "Cardiology",
        "description": "Narrowing of coronary arteries due to atherosclerosis.",
        "common_symptoms": "Chest pain, shortness of breath, fatigue",
        "severity_level": "Severe",
        "guideline_source": "AHA",
    },
    {
        "name": "Heart Failure",
        "category": "Cardiology",
        "description": "Condition where the heart cannot pump blood efficiently.",
        "common_symptoms": "Shortness of breath, leg swelling, fatigue",
        "severity_level": "Severe",
        "guideline_source": "ESC",
    },
    {
        "name": "Atrial Fibrillation",
        "category": "Cardiology",
        "description": "An irregular and often rapid heart rhythm that increases the risk of stroke and heart failure.",
        "common_symptoms": "Palpitations, dizziness, fatigue, chest discomfort",
        "severity_level": "Moderate",
        "guideline_source": "ESC",
    },
    {
        "name": "Myocardial Infarction",
        "category": "Cardiology",
        "description": "Damage to heart muscle caused by interruption of blood flow.",
        "common_symptoms": "Chest pain, sweating, nausea, shortness of breath",
        "severity_level": "Critical",
        "guideline_source": "AHA",
    },
    {
        "name": "Stable Angina",
        "category": "Cardiology",
        "description": "Chest pain caused by reduced blood flow to the heart during exertion.",
        "common_symptoms": "Chest tightness, fatigue, pain on exertion",
        "severity_level": "Moderate",
        "guideline_source": "AHA",
    },
    {
        "name": "Dilated Cardiomyopathy",
        "category": "Cardiology",
        "description": "Disease causing enlargement and weakening of the heart muscle.",
        "common_symptoms": "Fatigue, swelling of legs, breathlessness",
        "severity_level": "Severe",
        "guideline_source": "ESC",
    },
    {
        "name": "Pericarditis",
        "category": "Cardiology",
        "description": "Inflammation of the sac surrounding the heart.",
        "common_symptoms": "Sharp chest pain, fever, fatigue",
        "severity_level": "Moderate",
        "guideline_source": "ESC",
    },
    {
        "name": "Stroke",
        "category": "Neurology",
        "description": "Sudden interruption of blood supply to the brain.",
        "common_symptoms": "Weakness, facial drooping, slurred speech",
        "severity_level": "Critical",
        "guideline_source": "AHA",
    },
    {
        "name": "Transient Ischemic Attack",
        "category": "Neurology",
        "description": "Temporary interruption of blood flow to the brain without permanent damage.",
        "common_symptoms": "Temporary weakness, numbness, speech difficulty",
        "severity_level": "Moderate",
        "guideline_source": "AHA",
    },
    {
        "name": "Migraine",
        "category": "Neurology",
        "description": "Recurring headache disorder with neurological symptoms.",
        "common_symptoms": "Headache, nausea, sensitivity to light",
        "severity_level": "Moderate",
        "guideline_source": "NICE",
    },
    {
        "name": "Epilepsy",
        "category": "Neurology",
        "description": "Neurological disorder characterized by recurrent seizures.",
        "common_symptoms": "Seizures, confusion, loss of consciousness",
        "severity_level": "Severe",
        "guideline_source": "WHO",
    },
    {
        "name": "Parkinson's Disease",
        "category": "Neurology",
        "description": "Progressive neurodegenerative disorder affecting movement.",
        "common_symptoms": "Tremor, stiffness, slow movement",
        "severity_level": "Moderate",
        "guideline_source": "WHO",
    },
    {
        "name": "Alzheimer's Disease",
        "category": "Neurology",
        "description": "Progressive disorder causing memory loss and cognitive decline.",
        "common_symptoms": "Memory loss, confusion, behavioral changes",
        "severity_level": "Severe",
        "guideline_source": "WHO",
    },
    {
        "name": "Multiple Sclerosis",
        "category": "Neurology",
        "description": "Autoimmune disease affecting the brain and spinal cord.",
        "common_symptoms": "Vision problems, numbness, muscle weakness",
        "severity_level": "Severe",
        "guideline_source": "WHO",
    },
    {
        "name": "Bell's Palsy",
        "category": "Neurology",
        "description": "Sudden weakness of facial muscles due to nerve inflammation.",
        "common_symptoms": "Facial drooping, difficulty closing eye, altered taste",
        "severity_level": "Mild",
        "guideline_source": "NICE",
    },
    {
        "name": "Guillain-Barre Syndrome",
        "category": "Neurology",
        "description": "Rare autoimmune disorder affecting peripheral nerves.",
        "common_symptoms": "Muscle weakness, tingling, paralysis",
        "severity_level": "Critical",
        "guideline_source": "WHO",
    },
    {
        "name": "Meningitis",
        "category": "Neurology",
        "description": "Inflammation of the membranes surrounding the brain and spinal cord.",
        "common_symptoms": "Fever, neck stiffness, headache",
        "severity_level": "Critical",
        "guideline_source": "CDC",
    },
    {
        "name": "Asthma",
        "category": "Pulmonology",
        "description": "Chronic inflammatory disease of the airways.",
        "common_symptoms": "Wheezing, coughing, breathlessness",
        "severity_level": "Moderate",
        "guideline_source": "GINA",
    },
    {
        "name": "Chronic Obstructive Pulmonary Disease",
        "category": "Pulmonology",
        "description": "Progressive lung disease causing airflow limitation.",
        "common_symptoms": "Chronic cough, breathlessness, wheezing",
        "severity_level": "Severe",
        "guideline_source": "GOLD",
    },
    {
        "name": "Pneumonia",
        "category": "Pulmonology",
        "description": "Infection causing inflammation of the lungs.",
        "common_symptoms": "Fever, cough, chest pain",
        "severity_level": "Severe",
        "guideline_source": "WHO",
    },
    {
        "name": "Pulmonary Tuberculosis",
        "category": "Infectious Diseases",
        "description": "Bacterial infection caused by Mycobacterium tuberculosis.",
        "common_symptoms": "Persistent cough, weight loss, night sweats",
        "severity_level": "Severe",
        "guideline_source": "WHO",
    },
    {
        "name": "COVID-19",
        "category": "Infectious Diseases",
        "description": "Respiratory illness caused by SARS-CoV-2.",
        "common_symptoms": "Fever, cough, loss of smell, fatigue",
        "severity_level": "Moderate",
        "guideline_source": "WHO",
    },
        {
        "name": "Dengue Fever",
        "category": "Infectious Diseases",
        "description": "Mosquito-borne viral infection caused by the dengue virus.",
        "common_symptoms": "High fever, severe headache, joint pain, rash",
        "severity_level": "Moderate",
        "guideline_source": "WHO",
    },
    {
        "name": "Malaria",
        "category": "Infectious Diseases",
        "description": "Parasitic disease transmitted through Anopheles mosquitoes.",
        "common_symptoms": "Fever, chills, sweating, headache",
        "severity_level": "Severe",
        "guideline_source": "WHO",
    },
    {
        "name": "Typhoid Fever",
        "category": "Infectious Diseases",
        "description": "Systemic bacterial infection caused by Salmonella Typhi.",
        "common_symptoms": "High fever, abdominal pain, constipation, weakness",
        "severity_level": "Moderate",
        "guideline_source": "WHO",
    },
    {
        "name": "Cholera",
        "category": "Infectious Diseases",
        "description": "Acute diarrheal disease caused by Vibrio cholerae.",
        "common_symptoms": "Severe diarrhea, vomiting, dehydration",
        "severity_level": "Critical",
        "guideline_source": "WHO",
    },
    {
        "name": "Measles",
        "category": "Infectious Diseases",
        "description": "Highly contagious viral disease characterized by rash and fever.",
        "common_symptoms": "Fever, rash, cough, red eyes",
        "severity_level": "Moderate",
        "guideline_source": "WHO",
    },
    {
        "name": "Mumps",
        "category": "Infectious Diseases",
        "description": "Viral infection affecting the salivary glands.",
        "common_symptoms": "Swollen cheeks, fever, headache",
        "severity_level": "Moderate",
        "guideline_source": "CDC",
    },
    {
        "name": "Rubella",
        "category": "Infectious Diseases",
        "description": "Contagious viral infection also known as German measles.",
        "common_symptoms": "Rash, fever, swollen lymph nodes",
        "severity_level": "Mild",
        "guideline_source": "CDC",
    },
    {
        "name": "Chickenpox",
        "category": "Infectious Diseases",
        "description": "Viral infection caused by varicella-zoster virus.",
        "common_symptoms": "Itchy rash, fever, tiredness",
        "severity_level": "Moderate",
        "guideline_source": "CDC",
    },
    {
        "name": "Influenza",
        "category": "Infectious Diseases",
        "description": "Seasonal viral respiratory infection.",
        "common_symptoms": "Fever, body aches, cough, fatigue",
        "severity_level": "Moderate",
        "guideline_source": "CDC",
    },
    {
        "name": "Hepatitis A",
        "category": "Gastroenterology",
        "description": "Acute viral liver infection transmitted through contaminated food and water.",
        "common_symptoms": "Jaundice, fatigue, nausea, abdominal pain",
        "severity_level": "Moderate",
        "guideline_source": "WHO",
    },
    {
        "name": "Hepatitis C",
        "category": "Gastroenterology",
        "description": "Blood-borne viral infection affecting the liver.",
        "common_symptoms": "Fatigue, jaundice, abdominal discomfort",
        "severity_level": "Severe",
        "guideline_source": "WHO",
    },
    {
        "name": "Gastroesophageal Reflux Disease",
        "category": "Gastroenterology",
        "description": "Chronic acid reflux causing irritation of the esophagus.",
        "common_symptoms": "Heartburn, chest discomfort, regurgitation",
        "severity_level": "Mild",
        "guideline_source": "NICE",
    },
    {
        "name": "Peptic Ulcer Disease",
        "category": "Gastroenterology",
        "description": "Ulcers developing in the stomach or upper intestine.",
        "common_symptoms": "Burning stomach pain, bloating, nausea",
        "severity_level": "Moderate",
        "guideline_source": "NICE",
    },
    {
        "name": "Acute Pancreatitis",
        "category": "Gastroenterology",
        "description": "Sudden inflammation of the pancreas.",
        "common_symptoms": "Upper abdominal pain, vomiting, fever",
        "severity_level": "Severe",
        "guideline_source": "ACG",
    },
    {
        "name": "Chronic Pancreatitis",
        "category": "Gastroenterology",
        "description": "Long-term inflammation causing irreversible pancreatic damage.",
        "common_symptoms": "Abdominal pain, weight loss, oily stools",
        "severity_level": "Severe",
        "guideline_source": "ACG",
    },
    {
        "name": "Ulcerative Colitis",
        "category": "Gastroenterology",
        "description": "Inflammatory bowel disease affecting the colon.",
        "common_symptoms": "Bloody diarrhea, abdominal cramps, fatigue",
        "severity_level": "Moderate",
        "guideline_source": "ECCO",
    },
    {
        "name": "Crohn's Disease",
        "category": "Gastroenterology",
        "description": "Inflammatory bowel disease affecting any part of the digestive tract.",
        "common_symptoms": "Abdominal pain, diarrhea, weight loss",
        "severity_level": "Severe",
        "guideline_source": "ECCO",
    },
    {
        "name": "Irritable Bowel Syndrome",
        "category": "Gastroenterology",
        "description": "Functional bowel disorder causing recurrent abdominal discomfort.",
        "common_symptoms": "Bloating, abdominal pain, constipation, diarrhea",
        "severity_level": "Mild",
        "guideline_source": "NICE",
    },
    {
        "name": "Gallstone Disease",
        "category": "Gastroenterology",
        "description": "Formation of stones in the gallbladder.",
        "common_symptoms": "Upper abdominal pain, nausea, vomiting",
        "severity_level": "Moderate",
        "guideline_source": "NICE",
    },
    {
        "name": "Appendicitis",
        "category": "Gastroenterology",
        "description": "Inflammation of the appendix requiring urgent treatment.",
        "common_symptoms": "Right lower abdominal pain, fever, nausea",
        "severity_level": "Critical",
        "guideline_source": "ACS",
    },
    {
        "name": "Chronic Kidney Disease",
        "category": "Nephrology",
        "description": "Progressive decline in kidney function over time.",
        "common_symptoms": "Fatigue, swelling, decreased urine output",
        "severity_level": "Severe",
        "guideline_source": "KDIGO",
    },
    {
        "name": "Acute Kidney Injury",
        "category": "Nephrology",
        "description": "Sudden loss of kidney function.",
        "common_symptoms": "Reduced urine output, swelling, confusion",
        "severity_level": "Critical",
        "guideline_source": "KDIGO",
    },
    {
        "name": "Nephrotic Syndrome",
        "category": "Nephrology",
        "description": "Kidney disorder causing excessive protein loss in urine.",
        "common_symptoms": "Swelling, frothy urine, weight gain",
        "severity_level": "Severe",
        "guideline_source": "KDIGO",
    },
    {
        "name": "Glomerulonephritis",
        "category": "Nephrology",
        "description": "Inflammation of the kidney's filtering units.",
        "common_symptoms": "Blood in urine, swelling, high blood pressure",
        "severity_level": "Severe",
        "guideline_source": "KDIGO",
    },
    {
        "name": "Kidney Stones",
        "category": "Nephrology",
        "description": "Hard mineral deposits formed inside the kidneys.",
        "common_symptoms": "Severe flank pain, blood in urine, nausea",
        "severity_level": "Moderate",
        "guideline_source": "EAU",
    },
        {
        "name": "Psoriasis",
        "category": "Dermatology",
        "description": "A chronic autoimmune skin disorder characterized by red, scaly plaques.",
        "common_symptoms": "Red patches, silvery scales, itching",
        "severity_level": "Moderate",
        "guideline_source": "AAD",
    },
    {
        "name": "Atopic Dermatitis",
        "category": "Dermatology",
        "description": "A chronic inflammatory skin condition commonly known as eczema.",
        "common_symptoms": "Dry skin, itching, rash",
        "severity_level": "Moderate",
        "guideline_source": "AAD",
    },
    {
        "name": "Acne Vulgaris",
        "category": "Dermatology",
        "description": "A common inflammatory disorder of the sebaceous glands.",
        "common_symptoms": "Pimples, blackheads, oily skin",
        "severity_level": "Mild",
        "guideline_source": "AAD",
    },
    {
        "name": "Vitiligo",
        "category": "Dermatology",
        "description": "Autoimmune condition causing loss of skin pigmentation.",
        "common_symptoms": "White skin patches, premature graying",
        "severity_level": "Mild",
        "guideline_source": "AAD",
    },
    {
        "name": "Cellulitis",
        "category": "Dermatology",
        "description": "A bacterial infection affecting the deeper layers of the skin.",
        "common_symptoms": "Redness, swelling, fever, pain",
        "severity_level": "Severe",
        "guideline_source": "IDSA",
    },
    {
        "name": "Contact Dermatitis",
        "category": "Dermatology",
        "description": "Inflammation of the skin caused by contact with allergens or irritants.",
        "common_symptoms": "Red rash, itching, blisters",
        "severity_level": "Mild",
        "guideline_source": "AAD",
    },
    {
        "name": "Rosacea",
        "category": "Dermatology",
        "description": "Chronic inflammatory skin disease affecting the face.",
        "common_symptoms": "Facial redness, visible blood vessels, pimples",
        "severity_level": "Moderate",
        "guideline_source": "AAD",
    },
    {
        "name": "Melanoma",
        "category": "Dermatology",
        "description": "A malignant tumor arising from pigment-producing melanocytes.",
        "common_symptoms": "Changing mole, irregular borders, bleeding lesion",
        "severity_level": "Critical",
        "guideline_source": "NCCN",
    },
    {
        "name": "Basal Cell Carcinoma",
        "category": "Dermatology",
        "description": "The most common type of skin cancer.",
        "common_symptoms": "Pearly bump, non-healing sore",
        "severity_level": "Moderate",
        "guideline_source": "NCCN",
    },
    {
        "name": "Squamous Cell Carcinoma",
        "category": "Dermatology",
        "description": "Skin cancer arising from squamous cells.",
        "common_symptoms": "Scaly lesion, ulcer, crusting",
        "severity_level": "Moderate",
        "guideline_source": "NCCN",
    },
    {
        "name": "Rheumatoid Arthritis",
        "category": "Rheumatology",
        "description": "A chronic autoimmune disease affecting multiple joints.",
        "common_symptoms": "Joint pain, morning stiffness, swelling",
        "severity_level": "Severe",
        "guideline_source": "ACR",
    },
    {
        "name": "Osteoarthritis",
        "category": "Rheumatology",
        "description": "Degenerative joint disease caused by cartilage breakdown.",
        "common_symptoms": "Joint pain, stiffness, reduced movement",
        "severity_level": "Moderate",
        "guideline_source": "ACR",
    },
    {
        "name": "Systemic Lupus Erythematosus",
        "category": "Rheumatology",
        "description": "A systemic autoimmune disease affecting multiple organs.",
        "common_symptoms": "Butterfly rash, fatigue, joint pain",
        "severity_level": "Severe",
        "guideline_source": "EULAR",
    },
    {
        "name": "Ankylosing Spondylitis",
        "category": "Rheumatology",
        "description": "Inflammatory arthritis primarily affecting the spine.",
        "common_symptoms": "Back pain, stiffness, reduced flexibility",
        "severity_level": "Moderate",
        "guideline_source": "EULAR",
    },
    {
        "name": "Gout",
        "category": "Rheumatology",
        "description": "Inflammatory arthritis caused by uric acid crystal deposition.",
        "common_symptoms": "Sudden joint pain, redness, swelling",
        "severity_level": "Moderate",
        "guideline_source": "ACR",
    },
    {
        "name": "Iron Deficiency Anemia",
        "category": "Hematology",
        "description": "A condition caused by inadequate iron leading to reduced hemoglobin production.",
        "common_symptoms": "Fatigue, weakness, pale skin",
        "severity_level": "Moderate",
        "guideline_source": "WHO",
    },
    {
        "name": "Sickle Cell Disease",
        "category": "Hematology",
        "description": "Inherited blood disorder causing abnormally shaped red blood cells.",
        "common_symptoms": "Pain crises, fatigue, anemia",
        "severity_level": "Severe",
        "guideline_source": "WHO",
    },
    {
        "name": "Hemophilia A",
        "category": "Hematology",
        "description": "Inherited clotting disorder caused by factor VIII deficiency.",
        "common_symptoms": "Easy bruising, prolonged bleeding, joint bleeding",
        "severity_level": "Severe",
        "guideline_source": "WFH",
    },
    {
        "name": "Thalassemia Major",
        "category": "Hematology",
        "description": "Inherited blood disorder causing severe anemia.",
        "common_symptoms": "Fatigue, bone deformities, pale skin",
        "severity_level": "Critical",
        "guideline_source": "WHO",
    },
    {
        "name": "Immune Thrombocytopenic Purpura",
        "category": "Hematology",
        "description": "Autoimmune disorder resulting in low platelet count.",
        "common_symptoms": "Easy bruising, bleeding gums, petechiae",
        "severity_level": "Moderate",
        "guideline_source": "ASH",
    },
    {
        "name": "Depressive Disorder",
        "category": "Psychiatry",
        "description": "A mood disorder causing persistent sadness and loss of interest.",
        "common_symptoms": "Low mood, fatigue, poor concentration",
        "severity_level": "Severe",
        "guideline_source": "APA",
    },
    {
        "name": "Generalized Anxiety Disorder",
        "category": "Psychiatry",
        "description": "Persistent and excessive anxiety about everyday situations.",
        "common_symptoms": "Excessive worry, restlessness, insomnia",
        "severity_level": "Moderate",
        "guideline_source": "APA",
    },
    {
        "name": "Bipolar Disorder",
        "category": "Psychiatry",
        "description": "Mental disorder characterized by alternating manic and depressive episodes.",
        "common_symptoms": "Mood swings, impulsivity, depression",
        "severity_level": "Severe",
        "guideline_source": "APA",
    },
    {
        "name": "Schizophrenia",
        "category": "Psychiatry",
        "description": "Chronic psychiatric disorder affecting perception and thinking.",
        "common_symptoms": "Hallucinations, delusions, social withdrawal",
        "severity_level": "Critical",
        "guideline_source": "APA",
    },
    {
        "name": "Obsessive Compulsive Disorder",
        "category": "Psychiatry",
        "description": "Mental disorder involving intrusive thoughts and repetitive behaviors.",
        "common_symptoms": "Obsessions, compulsions, anxiety",
        "severity_level": "Moderate",
        "guideline_source": "APA",
    },
        {
        "name": "Breast Cancer",
        "category": "Oncology",
        "description": "A malignant tumor originating from breast tissue.",
        "common_symptoms": "Breast lump, nipple discharge, breast pain",
        "severity_level": "Critical",
        "guideline_source": "NCCN",
    },
    {
        "name": "Lung Cancer",
        "category": "Oncology",
        "description": "Cancer that begins in the lungs and may spread to other organs.",
        "common_symptoms": "Persistent cough, chest pain, weight loss",
        "severity_level": "Critical",
        "guideline_source": "NCCN",
    },
    {
        "name": "Colorectal Cancer",
        "category": "Oncology",
        "description": "Cancer affecting the colon or rectum.",
        "common_symptoms": "Blood in stool, abdominal pain, weight loss",
        "severity_level": "Critical",
        "guideline_source": "NCCN",
    },
    {
        "name": "Prostate Cancer",
        "category": "Oncology",
        "description": "Cancer developing in the prostate gland.",
        "common_symptoms": "Difficulty urinating, blood in urine, pelvic pain",
        "severity_level": "Critical",
        "guideline_source": "NCCN",
    },
    {
        "name": "Leukemia",
        "category": "Oncology",
        "description": "Cancer affecting blood-forming tissues including bone marrow.",
        "common_symptoms": "Fatigue, frequent infections, easy bruising",
        "severity_level": "Critical",
        "guideline_source": "NCCN",
    },
    {
        "name": "Lymphoma",
        "category": "Oncology",
        "description": "Cancer of the lymphatic system.",
        "common_symptoms": "Swollen lymph nodes, fever, night sweats",
        "severity_level": "Critical",
        "guideline_source": "NCCN",
    },
    {
        "name": "Cervical Cancer",
        "category": "Oncology",
        "description": "Cancer arising from the cervix.",
        "common_symptoms": "Abnormal vaginal bleeding, pelvic pain",
        "severity_level": "Critical",
        "guideline_source": "NCCN",
    },
    {
        "name": "Ovarian Cancer",
        "category": "Oncology",
        "description": "Cancer originating in the ovaries.",
        "common_symptoms": "Abdominal bloating, pelvic pain, loss of appetite",
        "severity_level": "Critical",
        "guideline_source": "NCCN",
    },
    {
        "name": "Glaucoma",
        "category": "Ophthalmology",
        "description": "Eye disease causing optic nerve damage due to high pressure.",
        "common_symptoms": "Blurred vision, eye pain, vision loss",
        "severity_level": "Severe",
        "guideline_source": "AAO",
    },
    {
        "name": "Cataract",
        "category": "Ophthalmology",
        "description": "Clouding of the eye lens leading to impaired vision.",
        "common_symptoms": "Blurred vision, glare, poor night vision",
        "severity_level": "Moderate",
        "guideline_source": "AAO",
    },
    {
        "name": "Diabetic Retinopathy",
        "category": "Ophthalmology",
        "description": "Retinal damage caused by diabetes.",
        "common_symptoms": "Blurred vision, floaters, vision loss",
        "severity_level": "Severe",
        "guideline_source": "AAO",
    },
    {
        "name": "Conjunctivitis",
        "category": "Ophthalmology",
        "description": "Inflammation of the conjunctiva caused by infection or allergy.",
        "common_symptoms": "Red eye, itching, discharge",
        "severity_level": "Mild",
        "guideline_source": "AAO",
    },
    {
        "name": "Otitis Media",
        "category": "ENT",
        "description": "Infection of the middle ear.",
        "common_symptoms": "Ear pain, fever, hearing difficulty",
        "severity_level": "Moderate",
        "guideline_source": "AAO-HNS",
    },
    {
        "name": "Chronic Sinusitis",
        "category": "ENT",
        "description": "Long-term inflammation of the paranasal sinuses.",
        "common_symptoms": "Facial pain, nasal congestion, headache",
        "severity_level": "Moderate",
        "guideline_source": "AAO-HNS",
    },
    {
        "name": "Tonsillitis",
        "category": "ENT",
        "description": "Inflammation of the tonsils caused by infection.",
        "common_symptoms": "Sore throat, fever, swollen tonsils",
        "severity_level": "Moderate",
        "guideline_source": "NICE",
    },
    {
        "name": "Benign Prostatic Hyperplasia",
        "category": "Urology",
        "description": "Non-cancerous enlargement of the prostate gland.",
        "common_symptoms": "Frequent urination, weak urine stream",
        "severity_level": "Moderate",
        "guideline_source": "EAU",
    },
    {
        "name": "Urinary Tract Infection",
        "category": "Urology",
        "description": "Bacterial infection involving the urinary tract.",
        "common_symptoms": "Burning urination, frequent urination, fever",
        "severity_level": "Moderate",
        "guideline_source": "IDSA",
    },
    {
        "name": "Endometriosis",
        "category": "Gynecology",
        "description": "Growth of endometrial tissue outside the uterus.",
        "common_symptoms": "Pelvic pain, painful menstruation, infertility",
        "severity_level": "Moderate",
        "guideline_source": "ACOG",
    },
    {
        "name": "Polycystic Ovary Syndrome",
        "category": "Gynecology",
        "description": "Hormonal disorder affecting ovarian function.",
        "common_symptoms": "Irregular periods, acne, weight gain",
        "severity_level": "Moderate",
        "guideline_source": "ESHRE",
    },
    {
        "name": "Ectopic Pregnancy",
        "category": "Gynecology",
        "description": "Pregnancy occurring outside the uterus.",
        "common_symptoms": "Abdominal pain, vaginal bleeding, dizziness",
        "severity_level": "Critical",
        "guideline_source": "ACOG",
    },
    {
        "name": "Cerebral Palsy",
        "category": "Pediatrics",
        "description": "Group of disorders affecting movement and posture due to early brain injury.",
        "common_symptoms": "Muscle stiffness, poor coordination, delayed milestones",
        "severity_level": "Severe",
        "guideline_source": "AAP",
    },
    {
        "name": "Autism Spectrum Disorder",
        "category": "Pediatrics",
        "description": "Neurodevelopmental disorder affecting communication and behavior.",
        "common_symptoms": "Social difficulties, repetitive behaviors, delayed speech",
        "severity_level": "Moderate",
        "guideline_source": "AAP",
    },
    {
        "name": "Attention Deficit Hyperactivity Disorder",
        "category": "Pediatrics",
        "description": "Neurodevelopmental disorder characterized by inattention and hyperactivity.",
        "common_symptoms": "Poor concentration, impulsiveness, hyperactivity",
        "severity_level": "Moderate",
        "guideline_source": "AAP",
    },
    {
        "name": "Osteoporosis",
        "category": "Orthopedics",
        "description": "Bone disease characterized by reduced bone density.",
        "common_symptoms": "Bone pain, fractures, loss of height",
        "severity_level": "Moderate",
        "guideline_source": "NOF",
    },
    {
        "name": "Lumbar Disc Herniation",
        "category": "Orthopedics",
        "description": "Displacement of an intervertebral disc causing nerve compression.",
        "common_symptoms": "Lower back pain, leg pain, numbness",
        "severity_level": "Moderate",
        "guideline_source": "AAOS",
    },
        {
        "name": "Myasthenia Gravis",
        "category": "Neurology",
        "description": "An autoimmune disorder causing weakness of skeletal muscles.",
        "common_symptoms": "Drooping eyelids, double vision, muscle weakness",
        "severity_level": "Severe",
        "guideline_source": "AAN",
    },
    {
        "name": "Amyotrophic Lateral Sclerosis",
        "category": "Neurology",
        "description": "Progressive neurodegenerative disease affecting motor neurons.",
        "common_symptoms": "Muscle weakness, difficulty speaking, muscle cramps",
        "severity_level": "Critical",
        "guideline_source": "AAN",
    },
    {
        "name": "Huntington Disease",
        "category": "Neurology",
        "description": "Inherited neurodegenerative disorder affecting movement and cognition.",
        "common_symptoms": "Involuntary movements, memory problems, mood changes",
        "severity_level": "Critical",
        "guideline_source": "AAN",
    },
    {
        "name": "Sarcoidosis",
        "category": "Pulmonology",
        "description": "Inflammatory disease characterized by granuloma formation in multiple organs.",
        "common_symptoms": "Persistent cough, fatigue, enlarged lymph nodes",
        "severity_level": "Moderate",
        "guideline_source": "ATS",
    },
    {
        "name": "Pulmonary Fibrosis",
        "category": "Pulmonology",
        "description": "Progressive scarring of lung tissue reducing respiratory function.",
        "common_symptoms": "Shortness of breath, dry cough, fatigue",
        "severity_level": "Severe",
        "guideline_source": "ATS",
    },
    {
        "name": "Bronchiectasis",
        "category": "Pulmonology",
        "description": "Permanent widening of the bronchi leading to recurrent infections.",
        "common_symptoms": "Chronic cough, sputum production, breathlessness",
        "severity_level": "Moderate",
        "guideline_source": "ERS",
    },
    {
        "name": "Wilson Disease",
        "category": "Gastroenterology",
        "description": "Inherited disorder causing excessive copper accumulation in the body.",
        "common_symptoms": "Jaundice, tremors, liver disease",
        "severity_level": "Severe",
        "guideline_source": "EASL",
    },
    {
        "name": "Hemochromatosis",
        "category": "Gastroenterology",
        "description": "Iron overload disorder affecting multiple organs.",
        "common_symptoms": "Fatigue, joint pain, liver enlargement",
        "severity_level": "Severe",
        "guideline_source": "AASLD",
    },
    {
        "name": "Diverticulitis",
        "category": "Gastroenterology",
        "description": "Inflammation or infection of diverticula in the colon.",
        "common_symptoms": "Lower abdominal pain, fever, constipation",
        "severity_level": "Moderate",
        "guideline_source": "AGA",
    },
    {
        "name": "Celiac Disease",
        "category": "Gastroenterology",
        "description": "Autoimmune disorder triggered by gluten consumption.",
        "common_symptoms": "Diarrhea, bloating, weight loss",
        "severity_level": "Moderate",
        "guideline_source": "ACG",
    },
    {
        "name": "Hyperthyroidism",
        "category": "Endocrinology",
        "description": "Overproduction of thyroid hormones.",
        "common_symptoms": "Weight loss, tremors, palpitations",
        "severity_level": "Moderate",
        "guideline_source": "ATA",
    },
    {
        "name": "Hypothyroidism",
        "category": "Endocrinology",
        "description": "Insufficient production of thyroid hormones.",
        "common_symptoms": "Fatigue, weight gain, constipation",
        "severity_level": "Moderate",
        "guideline_source": "ATA",
    },
    {
        "name": "Addison Disease",
        "category": "Endocrinology",
        "description": "Primary adrenal insufficiency causing cortisol deficiency.",
        "common_symptoms": "Fatigue, low blood pressure, weight loss",
        "severity_level": "Severe",
        "guideline_source": "Endocrine Society",
    },
    {
        "name": "Cushing Syndrome",
        "category": "Endocrinology",
        "description": "Condition caused by prolonged exposure to high cortisol levels.",
        "common_symptoms": "Weight gain, moon face, muscle weakness",
        "severity_level": "Severe",
        "guideline_source": "Endocrine Society",
    },
    {
        "name": "Paget Disease of Bone",
        "category": "Orthopedics",
        "description": "Chronic disorder resulting in enlarged and misshapen bones.",
        "common_symptoms": "Bone pain, deformities, fractures",
        "severity_level": "Moderate",
        "guideline_source": "NOF",
    },
    {
        "name": "Septic Arthritis",
        "category": "Orthopedics",
        "description": "Joint infection caused by bacteria or fungi.",
        "common_symptoms": "Joint pain, swelling, fever",
        "severity_level": "Critical",
        "guideline_source": "IDSA",
    },
    {
        "name": "Interstitial Cystitis",
        "category": "Urology",
        "description": "Chronic bladder condition causing pelvic pain and urinary urgency.",
        "common_symptoms": "Pelvic pain, urinary frequency, urgency",
        "severity_level": "Moderate",
        "guideline_source": "AUA",
    },
    {
        "name": "Testicular Torsion",
        "category": "Urology",
        "description": "Twisting of the spermatic cord causing loss of blood supply.",
        "common_symptoms": "Sudden testicular pain, swelling, nausea",
        "severity_level": "Critical",
        "guideline_source": "EAU",
    },
    {
        "name": "Pelvic Inflammatory Disease",
        "category": "Gynecology",
        "description": "Infection of the female reproductive organs.",
        "common_symptoms": "Pelvic pain, fever, abnormal discharge",
        "severity_level": "Moderate",
        "guideline_source": "CDC",
    },
    {
        "name": "Gestational Diabetes",
        "category": "Gynecology",
        "description": "Diabetes diagnosed during pregnancy.",
        "common_symptoms": "Increased thirst, frequent urination, fatigue",
        "severity_level": "Moderate",
        "guideline_source": "ADA",
    }

]

def seed():
    db = SessionLocal()
    try:
        inserted = 0
        for d in diseases:
            existing = db.query(Disease).filter_by(name=d["name"]).first()
            if not existing:
                db.add(Disease(**d))
                inserted += 1

        db.commit()
        print(
            f"Seeded {inserted} new diseases "
            f"(skipped {len(diseases) - inserted} duplicates)."
        )

    finally:
        db.close()


if __name__ == "__main__":
    seed()