from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class NLPAnalyzeRequest(BaseModel):
    """
    Request body for the NLP analysis endpoint.
    Accepts text input (typed, translated, or transcribed voice)
    along with optional session and patient identifiers.
    """
    text: str = Field(..., min_length=1, description="Patient symptom text. Can be in any language.")
    session_id: Optional[str] = Field(None, description="Session ID for multi-turn conversation memory.")
    patient_id: Optional[str] = Field(None, description="Patient identifier for record linkage.")

    class Config:
        json_schema_extra = {
            "example": {
                "text": "Mujhe severe chest pain hai aur breathlessness ho rahi hai",
                "session_id": "session-abc-123",
                "patient_id": "patient-001"
            }
        }


class NLPFollowupAction(BaseModel):
    """The follow-up question generated by the conversational engine."""
    question: str
    is_urgent: bool


class NLPMetadata(BaseModel):
    """Envelope metadata about the NLP processing run."""
    patient_id: Optional[str]
    session_id: str
    timestamp: str
    nlp_engine_version: str


class NLPAnalyzeResponse(BaseModel):
    """
    Full response envelope returned by the NLP pipeline.
    clinical_data is the structured Clinical JSON 
    followup_action contains the next question to ask the patient.
    """
    metadata: NLPMetadata
    clinical_data: Dict[str, Any]
    followup_action: NLPFollowupAction
